import { prisma } from "./src/lib/db";

async function identifyEnglishDescriptions() {
  try {
    const events = await prisma.event.findMany({
      select: {
        name: true,
        description: true,
        autoGenerated: true,
      },
    });

    console.log(`Totaal aantal events in database: ${events.length}`);

    // Simpele heuristiek: we zoeken naar typisch Engelse woorden
    // en we sluiten typisch Nederlandse woorden uit.
    const englishEvents = events.filter((e) => {
      if (!e.description) return false;
      const desc = e.description.toLowerCase();

      const hasEnglishWords =
        /\b(the|of|for|with|this|by|grants|removes|celebrates|dedicated to|lord|birth|anniversary|sun enters)\b/.test(
          desc
        );
      const hasDutchWords =
        /\b(de|het|een|wordt|gevierd|van|en|op|deze|dag|zijn|haar|naar|gewijd|aan)\b/.test(
          desc
        );

      return hasEnglishWords || !hasDutchWords;
    });

    console.log(
      `\nWe hebben ${englishEvents.length} events gevonden met waarschijnlijk een Engelse beschrijving:\n`
    );

    englishEvents.forEach((e) => {
      console.log(`Naam: ${e.name}`);
      console.log(`Beschrijving: ${e.description}`);
      console.log(`Automatisch gegenereerd: ${e.autoGenerated ? "Ja" : "Nee"}`);
      console.log("---");
    });
  } catch (error) {
    console.error("Fout bij het ophalen van events:", error);
  } finally {
    await prisma.$disconnect();
  }
}

identifyEnglishDescriptions();
