import { describe, it, expect, beforeEach, vi } from "vitest";
import { NextRequest } from "next/server";
import { prismaMock } from "@/__tests__/helpers/prisma-mock";
import { GET, DELETE, PUT } from "../events/[id]/route";
import { Prisma } from "@prisma/client";

/* eslint-disable @typescript-eslint/no-explicit-any */

const VALID_ID = "ckl9z5rte0000s6m1gj8h3x7d";

const MOCK_EVENT = {
  id: VALID_ID,
  name: "Test Event",
  description: null,
  eventType: "FESTIVAL" as never,
  recurrenceType: "NONE",
  categories: [],
  tithi: null,
  nakshatra: null,
  maas: null,
  tags: [],
  sankranti: null,
  isAdhikaOnly: false,
  includeAdhika: false,
  ruleType: null,
  ruleConfig: null,
  namingKey: null,
  autoGenerated: false,
  seriesParentEntries: [],
  seriesChildEntries: [],
  createdAt: new Date("2025-01-01T00:00:00.000Z"),
  updatedAt: new Date("2025-01-02T00:00:00.000Z"),
  occurrences: [
    {
      id: "occ_1",
      eventId: VALID_ID,
      date: new Date(2025, 0, 1),
      endDate: null,
      startTime: null,
      endTime: null,
      notes: null,
      createdAt: new Date("2025-01-01T00:00:00.000Z"),
      updatedAt: new Date("2025-01-02T00:00:00.000Z"),
    },
  ],
};

describe("API Events by ID", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("rejects invalid event IDs", async () => {
    const response = await GET(new NextRequest("http://localhost/api/events/bad"), {
      params: Promise.resolve({ id: "bad" }),
    });
    const json = await response.json();

    expect(response.status).toBe(400);
    expect(json.message).toBe("Ongeldig event ID formaat");
  });

  it("returns not found for missing events", async () => {
    prismaMock.event.findUnique.mockResolvedValue(null);

    const response = await GET(new NextRequest("http://localhost/api/events/test"), {
      params: Promise.resolve({ id: VALID_ID }),
    });
    const json = await response.json();

    expect(response.status).toBe(404);
    expect(json.error).toBe("NOT_FOUND");
  });

  it("returns event details when found with series mapping", async () => {
    prismaMock.event.findUnique.mockResolvedValue({
      ...MOCK_EVENT,
      seriesParentEntries: [{ child: { id: "c1", name: "Child 1" }, dayNumber: 1 }],
      seriesChildEntries: [{ parent: { id: "p1", name: "Parent 1" } }],
    } as never);

    const response = await GET(new NextRequest("http://localhost/api/events/test"), {
      params: Promise.resolve({ id: VALID_ID }),
    });
    const json = await response.json();

    expect(response.status).toBe(200);
    expect(json.id).toBe(VALID_ID);
    expect(json.parentEvents).toHaveLength(1);
    expect(json.childEvents).toHaveLength(1);
    expect(json.childEvents[0].dayNumber).toBe(1);
  });

  it("returns server error when GET fails", async () => {
    prismaMock.event.findUnique.mockRejectedValue(new Error("DB error"));

    const response = await GET(new NextRequest("http://localhost/api/events/test"), {
      params: Promise.resolve({ id: VALID_ID }),
    });
    const json = await response.json();

    expect(response.status).toBe(500);
    expect(json.message).toBe("Kon event niet ophalen");
  });

  it("rejects invalid update payloads", async () => {
    prismaMock.event.findUnique.mockResolvedValue(MOCK_EVENT as never);

    const request = new NextRequest("http://localhost/api/events/test", {
      method: "PUT",
      body: JSON.stringify({ date: "bad-date" }),
      headers: { "Content-Type": "application/json" },
    });

    const response = await PUT(request, {
      params: Promise.resolve({ id: VALID_ID }),
    });
    const json = await response.json();

    expect(response.status).toBe(400);
    expect(json.error).toBe("VALIDATION_ERROR");
  });

  it("updates event and first occurrence when payload is valid", async () => {
    prismaMock.event.findUnique.mockResolvedValue(MOCK_EVENT as never);
    prismaMock.$transaction.mockImplementation(async (operation) => {
      if (typeof operation === "function") {
        return operation(prismaMock);
      }
      return [];
    });
    prismaMock.event.update.mockResolvedValue({
      ...MOCK_EVENT,
      name: "Updated Event",
    } as never);
    prismaMock.eventOccurrence.update.mockResolvedValue({ id: "occ_1" } as never);

    const request = new NextRequest("http://localhost/api/events/test", {
      method: "PUT",
      body: JSON.stringify({
        name: "Updated Event",
        date: "2025-02-01",
      }),
      headers: { "Content-Type": "application/json" },
    });

    const response = await PUT(request, {
      params: Promise.resolve({ id: VALID_ID }),
    });
    const json = await response.json();

    expect(prismaMock.event.update).toHaveBeenCalledWith(
      expect.objectContaining({
        where: { id: VALID_ID },
        data: expect.objectContaining({
          name: "Updated Event",
        }),
      })
    );
    expect(response.status).toBe(200);
    expect(json.name).toBe("Updated Event");
  });

  it("updates primary category in PUT", async () => {
    prismaMock.event.findUnique.mockResolvedValue(MOCK_EVENT as never);
    prismaMock.category.findUnique.mockResolvedValue({ id: "cat_1" } as any);
    prismaMock.$transaction.mockImplementation(async (operation) => {
      if (typeof operation === "function") {
        return operation(prismaMock);
      }
      return [];
    });
    prismaMock.event.update.mockResolvedValue(MOCK_EVENT as never);

    const request = new NextRequest("http://localhost/api/events/test", {
      method: "PUT",
      body: JSON.stringify({ categoryId: "ckl9z5rte0000s6m1gj8h3x7c" }),
    });

    const response = await PUT(request, {
      params: Promise.resolve({ id: VALID_ID }),
    });

    expect(response.status).toBe(200);
    expect(prismaMock.eventCategory.deleteMany).toHaveBeenCalled();
    expect(prismaMock.eventCategory.upsert).toHaveBeenCalled();
  });

  it("handles Prisma errors in PUT", async () => {
    prismaMock.event.findUnique.mockResolvedValue(MOCK_EVENT as never);
    const error = new Prisma.PrismaClientKnownRequestError("Conflict", {
      code: "P2002",
      clientVersion: "5.0.0",
    });
    prismaMock.$transaction.mockRejectedValue(error);

    const request = new NextRequest("http://localhost/api/events/test", {
      method: "PUT",
      body: JSON.stringify({ name: "Conflict" }),
    });

    const response = await PUT(request, {
      params: Promise.resolve({ id: VALID_ID }),
    });
    expect(response.status).toBe(409);
  });

  it("returns 400 for related data not found in PUT", async () => {
    prismaMock.event.findUnique.mockResolvedValue(MOCK_EVENT as never);
    const error = new Prisma.PrismaClientKnownRequestError("FK failed", {
      code: "P2003",
      clientVersion: "5.0.0",
    });
    prismaMock.$transaction.mockRejectedValue(error);

    const request = new NextRequest("http://localhost/api/events/test", {
      method: "PUT",
      body: JSON.stringify({ name: "FK" }),
    });

    const response = await PUT(request, {
      params: Promise.resolve({ id: VALID_ID }),
    });
    expect(response.status).toBe(400);
  });

  it("returns 404 for record not found in PUT transaction", async () => {
    prismaMock.event.findUnique.mockResolvedValue(MOCK_EVENT as never);
    const error = new Prisma.PrismaClientKnownRequestError("Not found", {
      code: "P2025",
      clientVersion: "5.0.0",
    });
    prismaMock.$transaction.mockRejectedValue(error);

    const request = new NextRequest("http://localhost/api/events/test", {
      method: "PUT",
      body: JSON.stringify({ name: "Missing" }),
    });

    const response = await PUT(request, {
      params: Promise.resolve({ id: VALID_ID }),
    });
    expect(response.status).toBe(404);
  });

  it("deletes events when they exist", async () => {
    prismaMock.event.findUnique.mockResolvedValue({
      ...MOCK_EVENT,
      id: VALID_ID,
    } as never);
    prismaMock.event.delete.mockResolvedValue({
      ...MOCK_EVENT,
      id: VALID_ID,
    } as never);

    const response = await DELETE(new NextRequest("http://localhost/api/events/test"), {
      params: Promise.resolve({ id: VALID_ID }),
    });

    expect(prismaMock.event.delete).toHaveBeenCalledWith({
      where: { id: VALID_ID },
    });
    expect(response.status).toBe(204);
  });

  it("rejects invalid PUT event IDs", async () => {
    const response = await PUT(new NextRequest("http://localhost/api/events/bad"), {
      params: Promise.resolve({ id: "bad" }),
    });
    expect(response.status).toBe(400);
  });

  it("rejects invalid DELETE event IDs", async () => {
    const response = await DELETE(new NextRequest("http://localhost/api/events/bad"), {
      params: Promise.resolve({ id: "bad" }),
    });
    expect(response.status).toBe(400);
  });

  it("returns 404 for missing events in PUT", async () => {
    prismaMock.event.findUnique.mockResolvedValue(null);
    const request = new NextRequest("http://localhost/api/events/test", {
      method: "PUT",
      body: JSON.stringify({ name: "New Name" }),
    });
    const response = await PUT(request, {
      params: Promise.resolve({ id: VALID_ID }),
    });
    expect(response.status).toBe(404);
  });

  it("updates occurrence when date is provided in PUT", async () => {
    prismaMock.event.findUnique.mockResolvedValue(MOCK_EVENT as any);
    prismaMock.$transaction.mockImplementation(async (operation) => {
      if (typeof operation === "function") return operation(prismaMock);
      return [];
    });
    prismaMock.event.update.mockResolvedValue(MOCK_EVENT as any);
    prismaMock.eventOccurrence.update.mockResolvedValue({ id: "occ_1" } as any);

    const request = new NextRequest("http://localhost/api/events/test", {
      method: "PUT",
      body: JSON.stringify({ date: "2025-02-01" }),
    });

    const response = await PUT(request, {
      params: Promise.resolve({ id: VALID_ID }),
    });

    expect(response.status).toBe(200);
    expect(prismaMock.eventOccurrence.update).toHaveBeenCalled();
  });

  it("handles resetting categoryId to null in PUT", async () => {
    prismaMock.event.findUnique.mockResolvedValue(MOCK_EVENT as any);
    prismaMock.$transaction.mockImplementation(async (operation) => {
      if (typeof operation === "function") return operation(prismaMock);
      return [];
    });
    prismaMock.event.update.mockResolvedValue(MOCK_EVENT as any);

    const request = new NextRequest("http://localhost/api/events/test", {
      method: "PUT",
      body: JSON.stringify({ categoryId: null }),
    });

    const response = await PUT(request, {
      params: Promise.resolve({ id: VALID_ID }),
    });

    expect(response.status).toBe(200);
    expect(prismaMock.eventCategory.deleteMany).toHaveBeenCalled();
  });

  it("handles Prisma not found in DELETE", async () => {
    prismaMock.event.findUnique.mockResolvedValue(MOCK_EVENT as any);
    const error = new Prisma.PrismaClientKnownRequestError("Not found", {
      code: "P2025",
      clientVersion: "5.0.0",
    });
    prismaMock.event.delete.mockRejectedValue(error);

    const response = await DELETE(new NextRequest("http://localhost/api/events/test"), {
      params: Promise.resolve({ id: VALID_ID }),
    });
    expect(response.status).toBe(404);
  });

  it("returns server error when DELETE fails with unknown error", async () => {
    prismaMock.event.findUnique.mockResolvedValue(MOCK_EVENT as any);
    prismaMock.event.delete.mockRejectedValue(new Error("Unknown"));

    const response = await DELETE(new NextRequest("http://localhost/api/events/test"), {
      params: Promise.resolve({ id: VALID_ID }),
    });
    expect(response.status).toBe(500);
  });
});
