import { describe, it, expect, beforeEach, vi } from "vitest";
import { NextRequest } from "next/server";
import { prismaMock } from "@/__tests__/helpers/prisma-mock";
import { DEFAULT_LOCATION } from "@/lib/domain";

const { generateOccurrences, generateOccurrencesForEvents } = vi.hoisted(() => ({
  generateOccurrences: vi.fn(),
  generateOccurrencesForEvents: vi.fn(),
}));

vi.mock("@/services/recurrence", () => ({
  generateOccurrences,
  generateOccurrencesForEvents,
}));

/* eslint-disable @typescript-eslint/no-explicit-any */

import { POST } from "../events/generate-occurrences/route";

describe("POST /api/events/generate-occurrences", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    // Make $transaction execute the callback with prismaMock as the transaction client
    prismaMock.$transaction.mockImplementation(async (fn: any) => {
      if (typeof fn === "function") return await fn(prismaMock);
      return Promise.all(fn);
    });
  });

  it("requires start and end dates", async () => {
    const request = new NextRequest("http://localhost/api/events/generate-occurrences", {
      method: "POST",
      body: JSON.stringify({ endDate: "2025-01-02" }),
      headers: { "Content-Type": "application/json" },
    });

    const response = await POST(request);
    const json = await response.json();

    expect(response.status).toBe(400);
    expect(json.error).toBe("VALIDATION_ERROR");
  });

  it("returns not found when event does not exist", async () => {
    prismaMock.event.findUnique.mockResolvedValue(null);

    const request = new NextRequest("http://localhost/api/events/generate-occurrences", {
      method: "POST",
      body: JSON.stringify({
        eventId: "ckl9z5rte0000s6m1gj8h3x7d",
        startDate: "2025-01-01",
        endDate: "2025-01-02",
      }),
      headers: { "Content-Type": "application/json" },
    });

    const response = await POST(request);
    const json = await response.json();

    expect(response.status).toBe(404);
    expect(json.error).toBe("NOT_FOUND");
  });

  it("rejects invalid date formats", async () => {
    const request = new NextRequest("http://localhost/api/events/generate-occurrences", {
      method: "POST",
      body: JSON.stringify({
        startDate: "bad-date",
        endDate: "2025-01-02",
      }),
      headers: { "Content-Type": "application/json" },
    });

    const response = await POST(request);
    const json = await response.json();

    expect(response.status).toBe(400);
    expect(json.error).toBe("VALIDATION_ERROR");
  });

  it("returns early when event has no recurrence", async () => {
    prismaMock.event.findUnique.mockResolvedValue({
      id: "ckl9z5rte0000s6m1gj8h3x7d",
      name: "One-off",
      recurrenceType: "NONE",

      description: null,
      eventType: "OTHER",
      tithi: null,
      nakshatra: null,
      maas: null,
      tags: [],
      aliases: [],
      createdAt: new Date(),
      updatedAt: new Date(),
      sankranti: null,
      isAdhikaOnly: false,
      includeAdhika: false,
      ruleType: null,
      ruleConfig: null,
      namingKey: null,
      autoGenerated: false,
      startTime: null,
      endTime: null,
      timingType: null,
    });

    const request = new NextRequest("http://localhost/api/events/generate-occurrences", {
      method: "POST",
      body: JSON.stringify({
        eventId: "ckl9z5rte0000s6m1gj8h3x7d",
        startDate: "2025-01-01",
        endDate: "2025-01-02",
      }),
      headers: { "Content-Type": "application/json" },
    });

    const response = await POST(request);
    const json = await response.json();

    expect(response.status).toBe(200);
    expect(json.generated).toBe(0);
    expect(generateOccurrences).not.toHaveBeenCalled();
  });

  it("generates occurrences for a recurring event", async () => {
    prismaMock.event.findUnique.mockResolvedValue({
      id: "ckl9z5rte0000s6m1gj8h3x7d",
      name: "Recurring",
      recurrenceType: "YEARLY_LUNAR",

      description: null,
      eventType: "OTHER",
      tithi: null,
      nakshatra: null,
      maas: null,
      tags: [],
      aliases: [],
      createdAt: new Date(),
      updatedAt: new Date(),
      sankranti: null,
      isAdhikaOnly: false,
      includeAdhika: false,
      ruleType: null,
      ruleConfig: null,
      namingKey: null,
      autoGenerated: false,
      startTime: null,
      endTime: null,
      timingType: null,
    });
    generateOccurrences.mockResolvedValue([
      {
        date: new Date(2025, 0, 1),
        endDate: null,
        startTime: null,
        endTime: null,
        notes: null,
      },
      {
        date: new Date(2025, 0, 2),
        endDate: null,
        startTime: null,
        endTime: null,
        notes: null,
      },
    ]);
    prismaMock.eventOccurrence.createMany.mockResolvedValue({ count: 2 });

    const request = new NextRequest("http://localhost/api/events/generate-occurrences", {
      method: "POST",
      body: JSON.stringify({
        eventId: "ckl9z5rte0000s6m1gj8h3x7d",
        startDate: "2025-01-01",
        endDate: "2025-01-05",
      }),
      headers: { "Content-Type": "application/json" },
    });

    const response = await POST(request);
    const json = await response.json();

    expect(generateOccurrences).toHaveBeenCalledWith(
      expect.objectContaining({ id: "ckl9z5rte0000s6m1gj8h3x7d" }),
      expect.objectContaining({
        startDate: new Date("2025-01-01"),
        endDate: new Date("2025-01-05"),
      })
    );
    expect(prismaMock.eventOccurrence.createMany).toHaveBeenCalledTimes(1);
    expect(response.status).toBe(200);
    expect(json.generated).toBe(2);
  });

  it("uses DEFAULT_LOCATION when payload contains another generation location", async () => {
    prismaMock.event.findUnique.mockResolvedValue({
      id: "ckl9z5rte0000s6m1gj8h3x7d",
      name: "Recurring",
      recurrenceType: "YEARLY_LUNAR",

      description: null,
      eventType: "OTHER",
      tithi: null,
      nakshatra: null,
      maas: null,
      tags: [],
      aliases: [],
      createdAt: new Date(),
      updatedAt: new Date(),
      sankranti: null,
      isAdhikaOnly: false,
      includeAdhika: false,
      ruleType: null,
      ruleConfig: null,
      namingKey: null,
      autoGenerated: false,
      startTime: null,
      endTime: null,
      timingType: null,
    });
    generateOccurrences.mockResolvedValue([]);
    prismaMock.eventOccurrence.createMany.mockResolvedValue({ count: 0 });

    const request = new NextRequest("http://localhost/api/events/generate-occurrences", {
      method: "POST",
      body: JSON.stringify({
        eventId: "ckl9z5rte0000s6m1gj8h3x7d",
        startDate: "2025-01-01",
        endDate: "2025-01-05",
      }),
      headers: { "Content-Type": "application/json" },
    });

    await POST(request);

    expect(generateOccurrences).toHaveBeenCalledWith(
      expect.objectContaining({ id: "ckl9z5rte0000s6m1gj8h3x7d" }),
      expect.objectContaining({
        location: DEFAULT_LOCATION,
        timezone: DEFAULT_LOCATION.timezone,
      })
    );
  });

  it("generates occurrences for all recurring events", async () => {
    prismaMock.event.findMany.mockResolvedValue([
      {
        id: "ckl9z5rte0000s6m1gj8h3x7d",
        name: "Event 1",
        recurrenceType: "YEARLY_LUNAR",

        description: null,
        eventType: "OTHER",
        tithi: null,
        nakshatra: null,
        maas: null,
        tags: [],
        aliases: [],
        createdAt: new Date(),
        updatedAt: new Date(),
        sankranti: null,
        isAdhikaOnly: false,
        includeAdhika: false,
        ruleType: null,
        ruleConfig: null,
        namingKey: null,
        autoGenerated: false,
        startTime: null,
        endTime: null,
        timingType: null,
      },
      {
        id: "evt_2",
        name: "Event 2",
        recurrenceType: "MONTHLY_LUNAR",

        description: null,
        eventType: "OTHER",
        tithi: null,
        nakshatra: null,
        maas: null,
        tags: [],
        aliases: [],
        createdAt: new Date(),
        updatedAt: new Date(),
        sankranti: null,
        isAdhikaOnly: false,
        includeAdhika: false,
        ruleType: null,
        ruleConfig: null,
        namingKey: null,
        autoGenerated: false,
        startTime: null,
        endTime: null,
        timingType: null,
      },
    ]);
    generateOccurrencesForEvents.mockResolvedValue({
      results: new Map([
        [
          "ckl9z5rte0000s6m1gj8h3x7d",
          [
            {
              date: new Date(2025, 0, 1),
              endDate: null,
              startTime: null,
              endTime: null,
              notes: null,
            },
          ],
        ],
        ["evt_2", []],
      ]),
      failedCount: 0,
    });
    prismaMock.eventOccurrence.createMany.mockResolvedValue({ count: 1 });

    const request = new NextRequest("http://localhost/api/events/generate-occurrences", {
      method: "POST",
      body: JSON.stringify({
        startDate: "2025-01-01",
        endDate: "2025-01-05",
      }),
      headers: { "Content-Type": "application/json" },
    });

    const response = await POST(request);
    const json = await response.json();

    expect(generateOccurrencesForEvents).toHaveBeenCalledWith(
      expect.arrayContaining([
        expect.objectContaining({ id: "ckl9z5rte0000s6m1gj8h3x7d" }),
        expect.objectContaining({ id: "evt_2" }),
      ]),
      expect.objectContaining({
        startDate: new Date("2025-01-01"),
        endDate: new Date("2025-01-05"),
      })
    );
    expect(prismaMock.eventOccurrence.createMany).toHaveBeenCalledTimes(1);
    expect(response.status).toBe(200);
    expect(json.eventsProcessed).toBe(2);
    expect(json.generated).toBe(1);
  });

  it("returns 400 when startDate is after endDate", async () => {
    const request = new NextRequest("http://localhost/api/events/generate-occurrences", {
      method: "POST",
      body: JSON.stringify({
        startDate: "2025-01-05",
        endDate: "2025-01-01",
      }),
    });

    const response = await POST(request);
    const json = await response.json();
    expect(response.status).toBe(400);
    expect(json.message).toBe("startDate moet voor endDate liggen");
  });

  it("handles replace logic for single event", async () => {
    prismaMock.event.findUnique.mockResolvedValue({
      id: "ckl9z5rte0000s6m1gj8h3x7d",
      name: "Recurring",
      recurrenceType: "YEARLY_LUNAR",
      tags: [],
      aliases: [],
    } as any);
    generateOccurrences.mockResolvedValue([{ date: new Date() }]);
    prismaMock.eventOccurrence.deleteMany.mockResolvedValue({ count: 5 } as any);
    prismaMock.eventOccurrence.createMany.mockResolvedValue({ count: 1 } as any);

    const request = new NextRequest("http://localhost/api/events/generate-occurrences", {
      method: "POST",
      body: JSON.stringify({
        eventId: "ckl9z5rte0000s6m1gj8h3x7d",
        startDate: "2025-01-01",
        endDate: "2025-01-05",
        replace: true,
      }),
      headers: { "Content-Type": "application/json" },
    });

    const response = await POST(request);
    const json = await response.json();
    expect(response.status).toBe(200);
    expect(json.deleted).toBe(5);
    expect(prismaMock.eventOccurrence.deleteMany).toHaveBeenCalled();
  });

  it("handles no events with recurrence found in batch mode", async () => {
    prismaMock.event.findMany.mockResolvedValue([]);

    const request = new NextRequest("http://localhost/api/events/generate-occurrences", {
      method: "POST",
      body: JSON.stringify({
        startDate: "2025-01-01",
        endDate: "2025-01-05",
      }),
    });

    const response = await POST(request);
    const json = await response.json();
    expect(json.message).toContain("No events with recurrence found");
  });

  it("handles replace logic for batch generation", async () => {
    prismaMock.event.findMany.mockResolvedValue([
      {
        id: "ckl9z5rte0000s6m1gj8h3x7d",
        recurrenceType: "YEARLY_LUNAR",
        tags: [],
        aliases: [],
      } as any,
    ]);
    generateOccurrencesForEvents.mockResolvedValue({
      results: new Map([["ckl9z5rte0000s6m1gj8h3x7d", [{ date: new Date() }]]]),
      failedCount: 0,
    });
    prismaMock.eventOccurrence.deleteMany.mockResolvedValue({ count: 3 });
    prismaMock.eventOccurrence.createMany.mockResolvedValue({ count: 1 });

    const request = new NextRequest("http://localhost/api/events/generate-occurrences", {
      method: "POST",
      body: JSON.stringify({
        startDate: "2025-01-01",
        endDate: "2025-01-05",
        replace: true,
      }),
    });

    const response = await POST(request);
    const json = await response.json();
    expect(json.deleted).toBe(3);
    expect(prismaMock.eventOccurrence.deleteMany).toHaveBeenCalled();
  });

  it("returns 422 when batch generation has partial failures", async () => {
    prismaMock.event.findMany.mockResolvedValue([
      { id: "evt_1", recurrenceType: "YEARLY_LUNAR", tags: [], aliases: [] } as any,
    ]);
    generateOccurrencesForEvents.mockResolvedValue({
      results: new Map(),
      failedCount: 3,
    });

    const request = new NextRequest("http://localhost/api/events/generate-occurrences", {
      method: "POST",
      body: JSON.stringify({ startDate: "2025-01-01", endDate: "2025-01-05" }),
      headers: { "Content-Type": "application/json" },
    });

    const response = await POST(request);
    const json = await response.json();
    expect(response.status).toBe(422);
    expect(json.message).toMatch(/3 event/);
    expect(prismaMock.eventOccurrence.createMany).not.toHaveBeenCalled();
  });

  it("returns server error when generation fails", async () => {
    prismaMock.event.findMany.mockRejectedValue(new Error("DB error"));

    const request = new NextRequest("http://localhost/api/events/generate-occurrences", {
      method: "POST",
      body: JSON.stringify({
        startDate: "2025-01-01",
        endDate: "2025-01-05",
      }),
    });

    const response = await POST(request);
    const json = await response.json();
    expect(response.status).toBe(500);
    expect(json.message).toBe("Kon occurrences niet genereren");
  });
});
