import 'dotenv/config';
import { prisma } from '@/lib/db';

async function checkWhichEventsHaveOccurrences() {
  // Get all events with their occurrence counts
  const allEvents = await prisma.event.findMany({
    include: { _count: { select: { occurrences: true } } },
    orderBy: { name: 'asc' },
  });

  console.log(`\n📋 All Events (${allEvents.length} total):\n`);

  const withOccurrences = allEvents.filter(e => e._count.occurrences > 0);
  const withoutOccurrences = allEvents.filter(e => e._count.occurrences === 0);

  console.log(`✅ Events WITH occurrences (${withOccurrences.length}):`);
  for (const event of withOccurrences) {
    console.log(`  ${event.name}: ${event._count.occurrences} occ | ` +
      `ruleType: ${event.ruleType || 'none'} | ` +
      `recurrence: ${event.recurrenceType} | ` +
      `autoGen: ${event.autoGenerated}`);
  }

  console.log(`\n❌ Events WITHOUT occurrences (${withoutOccurrences.length}):`);
  for (const event of withoutOccurrences) {
    console.log(`  ${event.name} | ` +
      `ruleType: ${event.ruleType || 'none'} | ` +
      `recurrence: ${event.recurrenceType} | ` +
      `autoGen: ${event.autoGenerated}`);
  }

  // Check specifically SOLAR rule events
  const solarEvents = allEvents.filter(e => e.ruleType === 'SOLAR');
  console.log(`\n🌞 SOLAR Rule Events (${solarEvents.length}):`);
  for (const event of solarEvents) {
    console.log(`  ${event.name}: ${event._count.occurrences} occ | ` +
      `sankranti: ${event.sankranti} | ` +
      `ruleConfig: ${JSON.stringify(event.ruleConfig)}`);
  }

  // Check TITHI rule events
  const tithiEvents = allEvents.filter(e => e.ruleType === 'TITHI');
  console.log(`\n🌙 TITHI Rule Events (${tithiEvents.length}):`);
  for (const event of tithiEvents.slice(0, 5)) {
    console.log(`  ${event.name}: ${event._count.occurrences} occ | ` +
      `tithi: ${event.tithi} | ` +
      `maas: ${event.maas} | ` +
      `ruleConfig: ${JSON.stringify(event.ruleConfig)}`);
  }

  await prisma.$disconnect();
}

checkWhichEventsHaveOccurrences().catch(console.error);
