/**
 * One-time cleanup: remove legacy autoGenerated=false events from DB.
 *
 * These events were created by the old seed.ts (pre-catalog era) and have no
 * namingKey. They shadow the new catalog entries, preventing db:events from
 * creating the authoritative autoGenerated=true versions with proper namingKeys.
 *
 * Safe to run because:
 * - All these events are now defined in event-naming.ts catalog
 * - EventOccurrence records cascade-delete automatically (onDelete: Cascade)
 * - Run db:events + db:occurrences afterwards to regenerate everything cleanly
 *
 * Run with: npm run db:cleanup
 */
import "dotenv/config";
import { prisma } from "@/lib/db";

async function main() {
  const legacyEvents = await prisma.event.findMany({
    where: { autoGenerated: false, namingKey: null },
    select: { id: true, name: true },
    orderBy: { name: "asc" },
  });

  if (legacyEvents.length === 0) {
    console.log("✅ No legacy events found. Database is already clean.");
    return;
  }

  console.log(
    `🗑️  Found ${legacyEvents.length} legacy events (autoGenerated=false, namingKey=null):\n`
  );
  legacyEvents.forEach((e) => console.log(`   - ${e.name}`));

  const occCount = await prisma.eventOccurrence.count({
    where: { eventId: { in: legacyEvents.map((e) => e.id) } },
  });
  console.log(`\n   ${occCount} occurrences will also be deleted (cascade).`);

  const result = await prisma.event.deleteMany({
    where: { autoGenerated: false, namingKey: null },
  });

  console.log(`\n✅ Deleted ${result.count} events + ${occCount} occurrences.`);
  console.log("\n📋 Next steps (regenerate from catalog):");
  console.log("   npm run db:events");
  console.log(
    "   npm run db:occurrences -- --start 2026-01-01 --end 2029-12-31 --replace\n"
  );
}

main()
  .catch((e) => {
    console.error("❌ Error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    process.exit(0);
  });
