import 'dotenv/config';
import { prisma } from '@/lib/db';

async function finalReport() {
  // Count events by type
  const totalEvents = await prisma.event.count();
  const autoGenerated = await prisma.event.count({ where: { autoGenerated: true } });
  const manual = await prisma.event.count({ where: { autoGenerated: false } });

  const ekadashis = await prisma.event.count({
    where: { name: { contains: 'Ekadashi' } }
  });

  const sankrantis = await prisma.event.count({
    where: { ruleType: 'SOLAR' }
  });

  const purnimas = await prisma.event.count({
    where: { name: { contains: 'Purnima' } }
  });

  const jayantis = await prisma.event.count({
    where: { name: { contains: 'Jayanti' } }
  });

  // Count occurrences
  const totalOccurrences = await prisma.eventOccurrence.count();
  const occurrenceRange = await prisma.eventOccurrence.aggregate({
    _min: { date: true },
    _max: { date: true },
  });

  console.log('\n' + '='.repeat(70));
  console.log('📊 FINAL VALIDATION REPORT');
  console.log('='.repeat(70));

  console.log('\n📋 EVENTS IN DATABASE:');
  console.log(`  Total Events:        ${totalEvents}`);
  console.log(`  Auto-generated:      ${autoGenerated}`);
  console.log(`  Manual:              ${manual}`);

  console.log('\n📊 BY CATEGORY:');
  console.log(`  Ekadashis:           ${ekadashis}`);
  console.log(`  Sankrantis:          ${sankrantis}`);
  console.log(`  Purnimas:            ${purnimas}`);
  console.log(`  Jayantis:            ${jayantis}`);

  console.log('\n📅 OCCURRENCES GENERATED:');
  console.log(`  Total:               ${totalOccurrences}`);
  console.log(`  Date Range:          ${occurrenceRange._min.date?.toISOString().split('T')[0]} to ${occurrenceRange._max.date?.toISOString().split('T')[0]}`);

  console.log('\n✅ IMPLEMENTATION STATUS:');
  console.log('  ✓ Adhika Maas detection (29 days in 2026)');
  console.log('  ✓ Sankranti detection (36 sankrantis)');
  console.log('  ✓ Event naming catalog (60 events)');
  console.log('  ✓ Auto-generation system');
  console.log('  ✓ SOLAR rule engine (Sankrantis)');
  console.log('  ✓ TITHI rule engine (Ekadashis, Purnimas, etc.)');
  console.log('  ✓ Bug fix: Maas filtering for yearly events');

  console.log('\n📈 PROGRESS:');
  console.log(`  Started with:        48 events, 79 occurrences`);
  console.log(`  Now have:            ${totalEvents} events, ${totalOccurrences} occurrences`);
  console.log(`  Added:               ${totalEvents - 48} events, ${totalOccurrences - 79} occurrences`);

  console.log('\n' + '='.repeat(70));

  await prisma.$disconnect();
}

finalReport().catch(console.error);
