/**
 * Theme CSS Generator
 *
 * Generates globals.css from THEME_CATALOG.
 * Run with: npm run generate:css
 *
 * Output: src/app/globals.css (100% generated, do not edit manually)
 *
 * Features:
 * - Standard themes: CSS custom properties only
 * - Special themes: Full visual effects (backgrounds, animations, etc.)
 * - Utility classes: Theme-aware colors with hyphen notation (e.g., -10, -15)
 *
 * @see src/config/themes.ts - Source of truth
 */

import * as fs from "fs";
import * as path from "path";
import {
  THEME_CATALOG,
  getDefaultTheme,
  getStandardThemes,
  getSpecialThemes,
  type ThemeDefinition,
} from "../config/themes";
import { CATEGORY_CATALOG } from "../config/categories";

// =============================================================================
// HELPERS
// =============================================================================

/**
 * Normalize multiline CSS to single line (for background gradients etc).
 */
function normalizeCss(css: string): string {
  return css
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .join(" ")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Format CSS declarations with proper indentation.
 */
function formatCssBlock(css: string, indent: number = 2): string {
  const spaces = " ".repeat(indent);
  return css
    .split(";")
    .filter((rule) => rule.trim())
    .map((rule) => `${spaces}${rule.trim()};`)
    .join("\n");
}

/**
 * Get current date in YYYY-MM-DD format.
 */
function getCurrentDate(): string {
  const parts = new Date().toISOString().split("T");
  return parts[0] ?? "unknown";
}

// =============================================================================
// CSS SECTION GENERATORS
// =============================================================================

function generateHeader(): string {
  const standardCount = getStandardThemes().length;
  const specialCount = getSpecialThemes().length;

  return `@import "tailwindcss";

/* =============================================================================
   DHARMA CALENDAR - GENERATED THEME CSS
   
   ⚠️  DO NOT EDIT MANUALLY
   
   Generated by: npm run generate:css
   Source: src/config/themes.ts
   Date: ${getCurrentDate()}
   Themes: ${THEME_CATALOG.length} total (${standardCount} standard, ${specialCount} special)
   
   NOTE: Utility classes use HYPHEN notation (e.g., .bg-theme-primary-10)
         NOT slash notation (e.g., .bg-theme-primary/10)
   ============================================================================= */

/* Dark mode via class (Tailwind v4 convention) */
@custom-variant dark (&:where(.dark, .dark *));
`;
}

function generateRootVariables(): string {
  const defaultTheme = getDefaultTheme();

  return `
/* =============================================================================
   ROOT VARIABLES
   Default theme: ${defaultTheme.name}
   ============================================================================= */
:root {
  /* Light mode base colors */
  --background: #ffffff;
  --foreground: #171717;

  /* Theme colors (default: ${defaultTheme.name}) */
  --theme-primary: ${defaultTheme.colors.primary};
  --theme-secondary: ${defaultTheme.colors.secondary};
  --theme-accent: ${defaultTheme.colors.accent};

  /* Semantic aliases for Tailwind */
  --color-primary: var(--theme-primary);
  --color-secondary: var(--theme-secondary);
  --color-accent: var(--theme-accent);

  /* ═══════════════════════════════════════════════════════════════════════════
     SEMANTIC TOKENS - Theme-independent UI colors
     Use these instead of hardcoded zinc/gray values!
     ═══════════════════════════════════════════════════════════════════════════ */

  /* Backgrounds */
  --theme-bg: oklch(1 0 0);                          /* Page background */
  --theme-bg-subtle: oklch(0.985 0.002 60);          /* Subtle background (zinc-50) */
  --theme-surface: oklch(1 0 0);                     /* Cards, elevated surfaces */
  --theme-surface-raised: oklch(0.985 0.002 60);    /* Raised surface */
  --theme-surface-overlay: oklch(1 0 0 / 0.9);      /* Modals, dropdowns */

  /* Text colors */
  --theme-fg: oklch(0.141 0.005 285);               /* Primary text (zinc-900) */
  --theme-fg-secondary: oklch(0.442 0.017 285);     /* Secondary text (zinc-600) */
  --theme-fg-muted: oklch(0.552 0.016 286);         /* Muted text (zinc-500) */
  --theme-fg-subtle: oklch(0.705 0.015 286);        /* Subtle text (zinc-400) */

  /* Borders & Dividers */
  --theme-border: oklch(0.871 0.006 286);           /* Default border (zinc-200) */
  --theme-border-subtle: oklch(0.920 0.004 286);    /* Subtle border (zinc-100) */
  --theme-border-strong: oklch(0.705 0.015 286);    /* Strong border (zinc-400) */
  --theme-divider: oklch(0.920 0.004 286);          /* Dividers */

  /* Interactive states */
  --theme-hover: oklch(0.968 0.003 286);            /* Hover background (zinc-100) */
  --theme-active: oklch(0.920 0.004 286);           /* Active/pressed (zinc-200) */
  --theme-disabled: oklch(0.920 0.004 286);         /* Disabled elements */
  --theme-ring: var(--theme-primary);               /* Focus ring color */

  /* Status colors (extended for Fase 2) */
  --theme-success: oklch(0.65 0.15 145);
  --theme-success-bg: oklch(0.92 0.08 145);
  --theme-success-fg: oklch(0.35 0.14 145);
  --theme-success-border: oklch(0.75 0.12 145);

  --theme-warning: oklch(0.75 0.15 85);
  --theme-warning-bg: oklch(0.95 0.08 85);
  --theme-warning-fg: oklch(0.40 0.14 85);
  --theme-warning-border: oklch(0.75 0.14 85);

  --theme-error: oklch(0.60 0.20 25);
  --theme-error-bg: oklch(0.92 0.08 25);
  --theme-error-fg: oklch(0.35 0.18 25);
  --theme-error-border: oklch(0.75 0.16 25);

  --theme-info: oklch(0.60 0.12 240);
  --theme-info-bg: oklch(0.88 0.08 245);
  --theme-info-fg: oklch(0.42 0.12 245);
  --theme-info-border: oklch(0.75 0.14 245);

  /* Loading & Spinner */
  --theme-spinner-track: oklch(0.9 0.02 250 / 0.3);
  --theme-spinner-fill: var(--theme-primary);

  /* Glass & Overlay Effects */
  --theme-glass-bg: oklch(1 0 0 / 0.15);
  --theme-glass-border: oklch(1 0 0 / 0.2);
  --theme-modal-backdrop: oklch(0 0 0 / 0.6);

  /* Icon colors (celestial & UI) */
  --theme-icon-sun: oklch(0.85 0.18 60);           /* Bright yellow */
  --theme-icon-sunrise: oklch(0.75 0.20 45);       /* Vibrant orange */
  --theme-icon-sunset: oklch(0.60 0.22 20);        /* Rich red */
  --theme-icon-moon: oklch(0.72 0.16 210);         /* Cool blue */
  --theme-icon-event-special: oklch(0.85 0.18 60); /* Yellow (same as sun) */
  --theme-icon-mode-sun: oklch(0.85 0.18 60);      /* Mode toggle sun */
  --theme-icon-mode-moon: oklch(0.65 0.08 240);    /* Mode toggle moon */

  /* Moon Phase Visualization (default colors) */
  --theme-moon-surface-light: oklch(0.985 0.015 80);   /* Warm cream */
  --theme-moon-surface-mid: oklch(0.945 0.020 75);     /* Light beige */
  --theme-moon-surface-dark: oklch(0.895 0.025 70);    /* Medium sand */
  --theme-moon-shadow-light: oklch(0.165 0.015 280);   /* Dark blue-gray */
  --theme-moon-shadow-deep: oklch(0.105 0.010 275);    /* Deep indigo-black */
  --theme-moon-glow: oklch(0.980 0.035 85 / 0.7);      /* Soft golden glow */
  --theme-moon-rim: oklch(1 0 0 / 0.1);                /* Subtle white rim */

  /* Calendar-specific colors */
  --theme-calendar-header-text: oklch(0.5 0.02 250);
  --theme-calendar-date-text: oklch(0.4 0.02 250);
  --theme-calendar-today-text: white;
  --theme-calendar-off-range-text: oklch(0.7 0.01 250);
  --theme-calendar-agenda-text: inherit;
  --theme-calendar-off-range-bg: oklch(0.98 0.005 250);
  --theme-calendar-weekend-bg: oklch(0.97 0.01 60);
  --theme-calendar-popup-bg: white;
  --theme-calendar-today-bg: color-mix(in oklch, var(--theme-primary) 10%, transparent);
  --theme-calendar-border: oklch(0.9 0.01 250);
  --theme-calendar-border-subtle: oklch(0.92 0.01 250);
  --theme-calendar-full-moon-bg-start: oklch(0.97 0.04 85);
  --theme-calendar-full-moon-bg-end: oklch(0.95 0.06 75);
  --theme-calendar-full-moon-glow: oklch(1 0.05 85 / 0.3);
  --theme-calendar-new-moon-bg-start: oklch(0.96 0.02 280);
  --theme-calendar-new-moon-bg-end: oklch(0.94 0.03 270);

  /* Almanac-specific colors (Moon Phase Category - Blue/Indigo) */
  --theme-almanac-moon-bg: oklch(0.88 0.08 240);
  --theme-almanac-moon-fg: oklch(0.42 0.12 245);
  --theme-almanac-moon-focus: oklch(0.60 0.18 245);
  --theme-almanac-moon-cell-bg: oklch(0.86 0.06 270);
  --theme-almanac-moon-cell-bg-hover: oklch(0.82 0.08 270);
  --theme-almanac-moon-card-from: oklch(0.88 0.08 240);
  --theme-almanac-moon-card-to: oklch(0.86 0.06 270);
  --theme-almanac-moon-icon: oklch(0.55 0.16 245);
  --theme-almanac-moon-rise-icon: oklch(0.60 0.18 245);
  --theme-almanac-moon-set-icon: oklch(0.60 0.14 270);
  --theme-almanac-moon-badge-bg: oklch(0.88 0.08 240);
  --theme-almanac-moon-badge-fg: oklch(0.42 0.12 245);

  /* Almanac-specific colors (Special Days Category - Purple) */
  --theme-almanac-special-bg: oklch(0.87 0.08 295);
  --theme-almanac-special-fg: oklch(0.42 0.14 295);
  --theme-almanac-special-focus: oklch(0.60 0.20 295);
  --theme-almanac-special-cell-bg: oklch(0.90 0.04 295);
  --theme-almanac-special-cell-bg-hover: oklch(0.87 0.08 295);
  --theme-almanac-special-card-bg: oklch(0.90 0.04 295);
  --theme-almanac-special-heading: oklch(0.35 0.12 295);
  --theme-almanac-special-badge-bg: oklch(0.87 0.08 295);
  --theme-almanac-special-badge-fg: oklch(0.42 0.14 295);

  /* Almanac-specific colors (Events Category - Amber) */
  --theme-almanac-event-bg: oklch(0.88 0.10 75);
  --theme-almanac-event-fg: oklch(0.42 0.14 65);
  --theme-almanac-event-focus: oklch(0.60 0.18 70);
  --theme-almanac-event-cell-bg: oklch(0.92 0.06 75);
  --theme-almanac-event-cell-bg-hover: oklch(0.88 0.10 75);
  --theme-almanac-event-icon: oklch(0.60 0.18 70);
  --theme-almanac-event-major-bg: oklch(0.92 0.06 75);
  --theme-almanac-event-major-bg-hover: oklch(0.88 0.10 75);
  --theme-almanac-event-major-star: oklch(0.60 0.18 70);

  /* Almanac-specific colors (Sun Times Category - Orange/Yellow) */
  --theme-almanac-sun-rise-icon: oklch(0.65 0.20 50);
  --theme-almanac-sun-set-icon: oklch(0.58 0.22 25);
  --theme-almanac-sun-card-from: oklch(0.90 0.08 50);
  --theme-almanac-sun-card-to: oklch(0.94 0.08 90);
  --theme-almanac-sun-icon: oklch(0.60 0.18 50);

  /* Almanac-specific colors (Planetary Category - Vedic color-coded) */
  --theme-almanac-planet-moon: oklch(0.70 0.12 240);
  --theme-almanac-planet-mars: oklch(0.65 0.20 25);
  --theme-almanac-planet-mercury: oklch(0.70 0.18 145);
  --theme-almanac-planet-jupiter: oklch(0.75 0.18 95);
  --theme-almanac-planet-venus: oklch(0.75 0.14 345);
  --theme-almanac-planet-saturn: oklch(0.65 0.18 295);
  --theme-almanac-planet-sun: oklch(0.65 0.20 50);

  /* Almanac-specific colors (Warning/Inauspicious Category - Red) */
  --theme-almanac-warning-border: oklch(0.55 0.22 25);
  --theme-almanac-warning-bg: oklch(0.92 0.08 25);
  --theme-almanac-warning-heading: oklch(0.50 0.20 25);
  --theme-almanac-warning-text: oklch(0.38 0.16 25);

  /* Legacy aliases (for compatibility) */
  --color-success: var(--theme-success);
  --color-warning: var(--theme-warning);
  --color-error: var(--theme-error);
  --color-info: var(--theme-info);
}
`;
}

function generateDarkModeBase(): string {
  return `
/* =============================================================================
   DARK MODE BASE
   ============================================================================= */
.dark {
  --background: #0a0a0a;
  --foreground: #ededed;

  /* Dark mode semantic tokens */
  
  /* Backgrounds */
  --theme-bg: oklch(0.145 0.005 285);              /* Page background (zinc-900) */
  --theme-bg-subtle: oklch(0.21 0.006 285);        /* Subtle background (zinc-800) */
  --theme-surface: oklch(0.21 0.006 285);          /* Cards, elevated surfaces */
  --theme-surface-raised: oklch(0.274 0.006 286); /* Raised surface (zinc-700) */
  --theme-surface-overlay: oklch(0.21 0.006 285 / 0.95); /* Modals, dropdowns */

  /* Text colors */
  --theme-fg: oklch(0.968 0.003 286);              /* Primary text (zinc-100) */
  --theme-fg-secondary: oklch(0.705 0.015 286);   /* Secondary text (zinc-400) */
  --theme-fg-muted: oklch(0.552 0.016 286);       /* Muted text (zinc-500) */
  --theme-fg-subtle: oklch(0.442 0.017 285);      /* Subtle text (zinc-600) */

  /* Borders & Dividers */
  --theme-border: oklch(0.339 0.007 286);          /* Default border (zinc-700) */
  --theme-border-subtle: oklch(0.274 0.006 286);  /* Subtle border (zinc-800) */
  --theme-border-strong: oklch(0.442 0.017 285);  /* Strong border (zinc-600) */
  --theme-divider: oklch(0.274 0.006 286);         /* Dividers */

  /* Interactive states */
  --theme-hover: oklch(0.274 0.006 286);           /* Hover background (zinc-800) */
  --theme-active: oklch(0.339 0.007 286);          /* Active/pressed (zinc-700) */
  --theme-disabled: oklch(0.274 0.006 286);        /* Disabled elements */

  /* Status colors (extended for Fase 2 - dark mode) */
  --theme-success-bg: oklch(0.35 0.14 145 / 0.3);
  --theme-success-fg: oklch(0.75 0.12 145);
  --theme-success-border: oklch(0.55 0.15 145);

  --theme-warning-bg: oklch(0.40 0.14 85 / 0.3);
  --theme-warning-fg: oklch(0.80 0.14 85);
  --theme-warning-border: oklch(0.65 0.16 85);

  --theme-error-bg: oklch(0.35 0.18 25 / 0.3);
  --theme-error-fg: oklch(0.75 0.16 25);
  --theme-error-border: oklch(0.55 0.20 25);

  --theme-info-bg: oklch(0.35 0.12 245 / 0.3);
  --theme-info-fg: oklch(0.75 0.12 245);
  --theme-info-border: oklch(0.60 0.16 245);

  /* Loading & Spinner (dark mode) */
  --theme-spinner-track: oklch(0.3 0.02 250 / 0.3);
  --theme-spinner-fill: var(--theme-primary);

  /* Glass & Overlay Effects (dark mode) */
  --theme-glass-bg: oklch(1 0 0 / 0.08);
  --theme-glass-border: oklch(1 0 0 / 0.15);
  --theme-modal-backdrop: oklch(0 0 0 / 0.6);

  /* Icon colors - adjusted for dark mode visibility */
  --theme-icon-sun: oklch(0.80 0.16 50);           /* Golden yellow */
  --theme-icon-sunrise: oklch(0.72 0.18 35);       /* Warm amber */
  --theme-icon-sunset: oklch(0.65 0.20 15);        /* Brighter red */
  --theme-icon-moon: oklch(0.78 0.14 220);         /* Brighter blue */
  --theme-icon-event-special: oklch(0.80 0.16 50); /* Golden yellow */
  --theme-icon-mode-sun: oklch(0.85 0.18 60);      /* Bright in dark mode */
  --theme-icon-mode-moon: oklch(0.75 0.12 250);    /* More prominent */

  /* Moon Phase Visualization (dark mode - slightly cooler/brighter) */
  --theme-moon-surface-light: oklch(0.990 0.012 85);   /* Bright cream */
  --theme-moon-surface-mid: oklch(0.950 0.018 80);     /* Pale beige */
  --theme-moon-surface-dark: oklch(0.900 0.023 75);    /* Light sand */
  --theme-moon-shadow-light: oklch(0.110 0.012 275);   /* Very dark blue */
  --theme-moon-shadow-deep: oklch(0.065 0.008 270);    /* Near black indigo */
  --theme-moon-glow: oklch(0.985 0.030 90 / 0.6);      /* Cool silver glow */
  --theme-moon-rim: oklch(1 0 0 / 0.12);               /* Slightly brighter rim */

  /* Calendar-specific colors (dark mode) */
  --theme-calendar-header-text: oklch(0.7 0.02 250);
  --theme-calendar-date-text: oklch(0.8 0.02 250);
  --theme-calendar-today-text: white;
  --theme-calendar-off-range-text: oklch(0.5 0.01 250);
  --theme-calendar-agenda-text: oklch(0.85 0.02 250);
  --theme-calendar-off-range-bg: oklch(0.15 0.005 250);
  --theme-calendar-weekend-bg: oklch(0.18 0.01 60);
  --theme-calendar-popup-bg: oklch(0.2 0.01 250);
  --theme-calendar-today-bg: color-mix(in oklch, var(--theme-primary) 15%, transparent);
  --theme-calendar-border: oklch(0.3 0.01 250);
  --theme-calendar-border-subtle: oklch(0.25 0.01 250);
  --theme-calendar-full-moon-bg-start: oklch(0.25 0.04 85);
  --theme-calendar-full-moon-bg-end: oklch(0.22 0.06 75);
  --theme-calendar-full-moon-glow: oklch(0.4 0.08 85 / 0.3);
  --theme-calendar-new-moon-bg-start: oklch(0.18 0.03 280);
  --theme-calendar-new-moon-bg-end: oklch(0.16 0.04 270);

  /* Almanac-specific colors (Moon Phase Category - dark mode) */
  --theme-almanac-moon-bg: oklch(0.35 0.12 245 / 0.3);
  --theme-almanac-moon-fg: oklch(0.75 0.10 245);
  --theme-almanac-moon-focus: oklch(0.60 0.18 245);
  --theme-almanac-moon-cell-bg: oklch(0.35 0.10 270 / 0.2);
  --theme-almanac-moon-cell-bg-hover: oklch(0.35 0.10 270 / 0.3);
  --theme-almanac-moon-card-from: oklch(0.35 0.12 240 / 0.2);
  --theme-almanac-moon-card-to: oklch(0.35 0.10 270 / 0.2);
  --theme-almanac-moon-icon: oklch(0.55 0.16 245);
  --theme-almanac-moon-rise-icon: oklch(0.60 0.18 245);
  --theme-almanac-moon-set-icon: oklch(0.60 0.14 270);
  --theme-almanac-moon-badge-bg: oklch(0.35 0.12 245 / 0.3);
  --theme-almanac-moon-badge-fg: oklch(0.75 0.10 245);

  /* Almanac-specific colors (Special Days Category - dark mode) */
  --theme-almanac-special-bg: oklch(0.35 0.14 295 / 0.3);
  --theme-almanac-special-fg: oklch(0.75 0.12 295);
  --theme-almanac-special-focus: oklch(0.60 0.20 295);
  --theme-almanac-special-cell-bg: oklch(0.35 0.12 295 / 0.2);
  --theme-almanac-special-cell-bg-hover: oklch(0.35 0.12 295 / 0.3);
  --theme-almanac-special-card-bg: oklch(0.35 0.12 295 / 0.2);
  --theme-almanac-special-heading: oklch(0.75 0.12 295);
  --theme-almanac-special-badge-bg: oklch(0.35 0.14 295 / 0.3);
  --theme-almanac-special-badge-fg: oklch(0.75 0.12 295);

  /* Almanac-specific colors (Events Category - dark mode) */
  --theme-almanac-event-bg: oklch(0.40 0.14 70 / 0.3);
  --theme-almanac-event-fg: oklch(0.75 0.12 70);
  --theme-almanac-event-focus: oklch(0.60 0.18 70);
  --theme-almanac-event-cell-bg: oklch(0.40 0.14 75 / 0.2);
  --theme-almanac-event-cell-bg-hover: oklch(0.40 0.14 75 / 0.3);
  --theme-almanac-event-icon: oklch(0.60 0.18 70);
  --theme-almanac-event-major-bg: oklch(0.40 0.14 75 / 0.2);
  --theme-almanac-event-major-bg-hover: oklch(0.40 0.14 75 / 0.3);
  --theme-almanac-event-major-star: oklch(0.60 0.18 70);

  /* Almanac-specific colors (Sun Times Category - dark mode) */
  --theme-almanac-sun-rise-icon: oklch(0.65 0.20 50);
  --theme-almanac-sun-set-icon: oklch(0.58 0.22 25);
  --theme-almanac-sun-card-from: oklch(0.40 0.14 50 / 0.2);
  --theme-almanac-sun-card-to: oklch(0.42 0.14 90 / 0.2);
  --theme-almanac-sun-icon: oklch(0.60 0.18 50);

  /* Almanac-specific colors (Planetary Category - dark mode) */
  --theme-almanac-planet-moon: oklch(0.70 0.12 240);
  --theme-almanac-planet-mars: oklch(0.65 0.20 25);
  --theme-almanac-planet-mercury: oklch(0.70 0.18 145);
  --theme-almanac-planet-jupiter: oklch(0.75 0.18 95);
  --theme-almanac-planet-venus: oklch(0.75 0.14 345);
  --theme-almanac-planet-saturn: oklch(0.65 0.18 295);
  --theme-almanac-planet-sun: oklch(0.65 0.20 50);

  /* Almanac-specific colors (Warning/Inauspicious Category - dark mode) */
  --theme-almanac-warning-border: oklch(0.55 0.22 25);
  --theme-almanac-warning-bg: oklch(0.38 0.18 25 / 0.2);
  --theme-almanac-warning-heading: oklch(0.65 0.20 25);
  --theme-almanac-warning-text: oklch(0.75 0.14 25);
}
`;
}

function generateStandardThemes(): string {
  const standardThemes = getStandardThemes(); // Gets both classic and revamped

  const blocks = standardThemes.map((theme) => {
    const isRevamped = theme.category === "revamped";

    let css = `
/* Theme: ${theme.displayName} ${isRevamped ? '(Revamped with gradients)' : '(Classic)'} */
[data-theme="${theme.name}"] {
  --theme-primary: ${theme.colors.primary};
  --theme-secondary: ${theme.colors.secondary};
  --theme-accent: ${theme.colors.accent};
}`;

    // Add background gradients for revamped themes
    if (isRevamped && theme.background) {
      css += `

/* Background (Light) */
[data-theme="${theme.name}"] body {
  background: ${normalizeCss(theme.background.light)};
  background-attachment: fixed;
}

/* Page backgrounds - transparent to show gradient */
[data-theme="${theme.name}"] .bg-theme-bg,
[data-theme="${theme.name}"] .bg-theme-bg-subtle {
  background: transparent !important;
}

/* Cards and surfaces - glassmorphism effect for better contrast */
[data-theme="${theme.name}"] .bg-theme-surface {
  background: oklch(1 0 0 / 0.70) !important;
  backdrop-filter: blur(12px);
  border-color: oklch(1 0 0 / 0.30) !important;
}

[data-theme="${theme.name}"] .bg-theme-surface-raised {
  background: oklch(1 0 0 / 0.80) !important;
  backdrop-filter: blur(16px);
  border-color: oklch(1 0 0 / 0.40) !important;
}

/* Background (Dark) */
.dark[data-theme="${theme.name}"] body,
[data-theme="${theme.name}"].dark body {
  background: ${normalizeCss(theme.background.dark)};
  background-attachment: fixed;
}

/* Page backgrounds - dark mode transparent */
.dark[data-theme="${theme.name}"] .bg-theme-bg,
[data-theme="${theme.name}"].dark .bg-theme-bg,
.dark[data-theme="${theme.name}"] .bg-theme-bg-subtle,
[data-theme="${theme.name}"].dark .bg-theme-bg-subtle {
  background: transparent !important;
}

/* Cards and surfaces - dark mode glassmorphism */
.dark[data-theme="${theme.name}"] .bg-theme-surface,
[data-theme="${theme.name}"].dark .bg-theme-surface {
  background: oklch(0.18 0.01 270 / 0.75) !important;
  backdrop-filter: blur(12px);
  border-color: oklch(1 0 0 / 0.10) !important;
}

.dark[data-theme="${theme.name}"] .bg-theme-surface-raised,
[data-theme="${theme.name}"].dark .bg-theme-surface-raised {
  background: oklch(0.22 0.01 270 / 0.85) !important;
  backdrop-filter: blur(16px);
  border-color: oklch(1 0 0 / 0.15) !important;
}`;
    }

    return css;
  }).join("\n");

  return `
/* =============================================================================
   STANDARD THEMES (Classic + Revamped)
   ============================================================================= */
${blocks}
`;
}

function generateSpecialTheme(theme: ThemeDefinition): string {
  if (!theme.isSpecial) return "";

  const parts: string[] = [];
  const n = theme.name;

  // Base colors + custom properties
  let customProps = "";
  if (theme.specialStyles?.customProperties) {
    customProps = Object.entries(theme.specialStyles.customProperties)
      .map(([key, value]) => `  ${key}: ${value};`)
      .join("\n");
  }

  parts.push(`
/* ═══════════════════════════════════════════════════════════════════════════
   ✨ SPECIAL THEME: ${theme.displayName}
   ${theme.description}
   ═══════════════════════════════════════════════════════════════════════════ */

/* Base colors */
[data-theme="${n}"] {
  --theme-primary: ${theme.colors.primary};
  --theme-secondary: ${theme.colors.secondary};
  --theme-accent: ${theme.colors.accent};
${customProps}
}`);

  // Background
  if (theme.background) {
    parts.push(`
/* Background (Light) */
[data-theme="${n}"] body {
  background: ${normalizeCss(theme.background.light)};
  background-attachment: fixed;
}

/* Make main container transparent */
[data-theme="${n}"] .min-h-screen {
  background: transparent !important;
}

/* Background (Dark) */
.dark[data-theme="${n}"] body,
[data-theme="${n}"].dark body {
  background: ${normalizeCss(theme.background.dark)};
  background-attachment: fixed;
}`);
  }

  // Component styles
  type ComponentMapEntry =
    | { key: string; selector: string; selectors?: undefined; name: string }
    | { key: string; selector?: undefined; selectors: readonly string[]; name: string };

  const componentMap: readonly ComponentMapEntry[] = [
    { key: "header", selector: "header", name: "Header" },
    { key: "cards", selectors: [".bg-white", ".rounded-2xl.shadow-lg"], name: "Cards" },
    { key: "buttons", selector: ".bg-theme-primary", name: "Primary Buttons" },
    { key: "inputs", selectors: ["input", "select", "textarea"], name: "Inputs" },
    { key: "headings", selector: "h1", name: "Headings" },
  ];

  for (const entry of componentMap) {
    const { key, name } = entry;
    const styles = theme.specialStyles?.[key as keyof typeof theme.specialStyles];
    if (!styles || typeof styles !== "object" || !("light" in styles)) continue;

    let sel: string;
    let darkSel: string;

    if ("selectors" in entry && entry.selectors) {
      sel = entry.selectors.map((s: string) => `[data-theme="${n}"] ${s}`).join(",\n");
      darkSel = entry.selectors
        .flatMap((s: string) => [
          `.dark[data-theme="${n}"] ${s}`,
          `[data-theme="${n}"].dark ${s}`,
        ])
        .join(",\n");
    } else if ("selector" in entry && entry.selector) {
      sel = `[data-theme="${n}"] ${entry.selector}`;
      darkSel = `.dark[data-theme="${n}"] ${entry.selector},\n[data-theme="${n}"].dark ${entry.selector}`;
    } else {
      continue;
    }

    parts.push(`
/* ${name} (Light) */
${sel} {
${formatCssBlock(styles.light)}
}

/* ${name} (Dark) */
${darkSel} {
${formatCssBlock(styles.dark)}
}`);
  }

  // Animations
  if (theme.specialStyles?.animations?.length) {
    const keyframes = theme.specialStyles.animations
      .map(
        (anim) => `
@keyframes ${anim.name} {
${anim.keyframes
  .split("\n")
  .map((l) => l.trim())
  .filter((l) => l)
  .map((l) => `  ${l}`)
  .join("\n")}
}`
      )
      .join("\n");

    parts.push(`
/* Animations */
${keyframes}`);
  }

  // Decorations
  if (theme.specialStyles?.decorations) {
    parts.push(`
/* Decorations (Light) */
[data-theme="${n}"] body::after {
${formatCssBlock(theme.specialStyles.decorations.light)}
}

/* Decorations (Dark) */
.dark[data-theme="${n}"] body::after,
[data-theme="${n}"].dark body::after {
${formatCssBlock(theme.specialStyles.decorations.dark)}
}`);
  }

  // Additional CSS
  if (theme.specialStyles?.additionalCss) {
    parts.push(`
/* Additional Styles */
${theme.specialStyles.additionalCss}`);
  }

  return parts.join("\n");
}

function generateSpecialThemesSection(): string {
  const specialThemes = getSpecialThemes();
  if (specialThemes.length === 0) return "";

  return `
/* =============================================================================
   ✨ SPECIAL THEMES ✨
   Premium themes with enhanced visual effects
   ============================================================================= */
${specialThemes.map(generateSpecialTheme).join("\n")}
`;
}

function generateTailwindIntegration(): string {
  return `
/* =============================================================================
   TAILWIND INTEGRATION
   ============================================================================= */
@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --color-primary: var(--theme-primary);
  --color-secondary: var(--theme-secondary);
  --color-accent: var(--theme-accent);
  --font-sans: var(--font-geist-sans);
  --font-mono: var(--font-geist-mono);
}
`;
}

function generateBaseStyles(): string {
  return `
/* =============================================================================
   BASE STYLES
   ============================================================================= */
body {
  background: var(--background);
  color: var(--foreground);
  font-family: var(--font-sans), system-ui, sans-serif;
  min-height: 100vh;
}

html {
  scroll-behavior: smooth;
}

/* Focus ring using theme color */
*:focus-visible {
  outline: 2px solid var(--theme-primary);
  outline-offset: 2px;
}

/* Selection using theme color */
::selection {
  background-color: color-mix(in oklch, var(--theme-primary) 30%, transparent);
  color: var(--foreground);
}
`;
}

function generateUtilityClasses(): string {
  // Using HYPHEN notation for opacity variants (e.g., -10, -15, -20)
  // This avoids CSS escaping issues and is more readable
  return `
/* =============================================================================
   THEME UTILITY CLASSES
   
   IMPORTANT: Use HYPHEN notation for opacity variants!
   ✅ Correct: .bg-theme-primary-10
   ❌ Wrong:   .bg-theme-primary/10
   ============================================================================= */

/* === SOLID BACKGROUNDS === */
.bg-theme-primary { background-color: var(--theme-primary); }
.bg-theme-secondary { background-color: var(--theme-secondary); }
.bg-theme-accent { background-color: var(--theme-accent); }

/* === BACKGROUND WITH OPACITY (hyphen notation) === */
.bg-theme-primary-10 { background-color: color-mix(in oklch, var(--theme-primary) 10%, transparent); }
.bg-theme-primary-15 { background-color: color-mix(in oklch, var(--theme-primary) 15%, transparent); }
.bg-theme-primary-20 { background-color: color-mix(in oklch, var(--theme-primary) 20%, transparent); }
.bg-theme-primary-30 { background-color: color-mix(in oklch, var(--theme-primary) 30%, transparent); }
.bg-theme-primary-50 { background-color: color-mix(in oklch, var(--theme-primary) 50%, transparent); }

.bg-theme-secondary-10 { background-color: color-mix(in oklch, var(--theme-secondary) 10%, transparent); }
.bg-theme-secondary-15 { background-color: color-mix(in oklch, var(--theme-secondary) 15%, transparent); }
.bg-theme-secondary-20 { background-color: color-mix(in oklch, var(--theme-secondary) 20%, transparent); }

.bg-theme-accent-10 { background-color: color-mix(in oklch, var(--theme-accent) 10%, transparent); }
.bg-theme-accent-15 { background-color: color-mix(in oklch, var(--theme-accent) 15%, transparent); }
.bg-theme-accent-20 { background-color: color-mix(in oklch, var(--theme-accent) 20%, transparent); }

/* === TEXT COLORS === */
.text-theme-primary { color: var(--theme-primary); }
.text-theme-secondary { color: var(--theme-secondary); }
.text-theme-accent { color: var(--theme-accent); }

/* === BORDER COLORS === */
.border-theme-primary { border-color: var(--theme-primary); }
.border-theme-secondary { border-color: var(--theme-secondary); }
.border-theme-accent { border-color: var(--theme-accent); }
.border-theme-primary-30 { border-color: color-mix(in oklch, var(--theme-primary) 30%, transparent); }
.border-theme-primary-50 { border-color: color-mix(in oklch, var(--theme-primary) 50%, transparent); }

/* === RING COLORS === */
.ring-theme-primary { --tw-ring-color: var(--theme-primary); }
.ring-theme-primary-30 { --tw-ring-color: color-mix(in oklch, var(--theme-primary) 30%, transparent); }
.ring-theme-primary-50 { --tw-ring-color: color-mix(in oklch, var(--theme-primary) 50%, transparent); }

/* === SHADOWS === */
.shadow-theme-primary {
  box-shadow: 0 4px 14px 0 color-mix(in oklch, var(--theme-primary) 25%, transparent);
}
.shadow-theme-primary-lg {
  box-shadow: 0 10px 25px -3px color-mix(in oklch, var(--theme-primary) 30%, transparent);
}

/* === SEMANTIC BACKGROUNDS === */
.bg-theme-bg { background-color: var(--theme-bg); }
.bg-theme-bg-subtle { background-color: var(--theme-bg-subtle); }
.bg-theme-surface { background-color: var(--theme-surface); }
.bg-theme-surface-raised { background-color: var(--theme-surface-raised); }
.bg-theme-surface-overlay { background-color: var(--theme-surface-overlay); }
.bg-theme-hover { background-color: var(--theme-hover); }
.bg-theme-active { background-color: var(--theme-active); }

/* === SEMANTIC TEXT === */
.text-theme-fg { color: var(--theme-fg); }
.text-theme-fg-secondary { color: var(--theme-fg-secondary); }
.text-theme-fg-muted { color: var(--theme-fg-muted); }
.text-theme-fg-subtle { color: var(--theme-fg-subtle); }

/* === SEMANTIC BORDERS === */
.border-theme-border { border-color: var(--theme-border); }
.border-theme-border-subtle { border-color: var(--theme-border-subtle); }
.border-theme-border-strong { border-color: var(--theme-border-strong); }
.divide-theme-divider > :not([hidden]) ~ :not([hidden]) { border-color: var(--theme-divider); }

/* === STATUS COLORS === */
.bg-theme-success { background-color: var(--theme-success); }
.bg-theme-success-subtle { background-color: var(--theme-success-bg); }
.text-theme-success { color: var(--theme-success); }
.border-theme-success { border-color: var(--theme-success); }

.bg-theme-warning { background-color: var(--theme-warning); }
.bg-theme-warning-subtle { background-color: var(--theme-warning-bg); }
.text-theme-warning { color: var(--theme-warning); }
.border-theme-warning { border-color: var(--theme-warning); }

.bg-theme-error { background-color: var(--theme-error); }
.bg-theme-error-subtle { background-color: var(--theme-error-bg); }
.text-theme-error { color: var(--theme-error); }
.border-theme-error { border-color: var(--theme-error); }

.bg-theme-info { background-color: var(--theme-info); }
.bg-theme-info-subtle { background-color: var(--theme-info-bg); }
.text-theme-info { color: var(--theme-info); }
.border-theme-info { border-color: var(--theme-info); }

/* === ICON COLORS === */
.text-theme-icon-sun { color: var(--theme-icon-sun); }
.text-theme-icon-sunrise { color: var(--theme-icon-sunrise); }
.text-theme-icon-sunset { color: var(--theme-icon-sunset); }
.text-theme-icon-moon { color: var(--theme-icon-moon); }
.text-theme-icon-event-special { color: var(--theme-icon-event-special); }
.text-theme-icon-mode-sun { color: var(--theme-icon-mode-sun); }
.text-theme-icon-mode-moon { color: var(--theme-icon-mode-moon); }

/* === GRADIENTS === */
.bg-theme-gradient {
  background: linear-gradient(135deg, var(--theme-primary), var(--theme-accent));
}
.bg-theme-gradient-to-r {
  background: linear-gradient(to right, var(--theme-primary), var(--theme-accent));
}
.bg-theme-gradient-subtle {
  background: linear-gradient(
    135deg,
    color-mix(in oklch, var(--theme-primary) 10%, transparent),
    color-mix(in oklch, var(--theme-accent) 10%, transparent)
  );
}

/* === HOVER STATES === */
.hover-bg-theme-primary:hover { background-color: var(--theme-primary); }
.hover-bg-theme-primary-20:hover { background-color: color-mix(in oklch, var(--theme-primary) 20%, transparent); }
.hover-text-theme-primary:hover { color: var(--theme-primary); }
.hover-border-theme-primary:hover { border-color: var(--theme-primary); }

/* === FOCUS STATES === */
.focus-ring-theme-primary:focus { --tw-ring-color: var(--theme-primary); }
.focus-border-theme-primary:focus { border-color: var(--theme-primary); }
`;
}

function generateAnimations(): string {
  return `
/* =============================================================================
   GLOBAL ANIMATIONS
   ============================================================================= */
@keyframes slide-in-from-right {
  from { transform: translateX(100%); opacity: 0; }
  to { transform: translateX(0); opacity: 1; }
}

@keyframes fade-in {
  from { opacity: 0; }
  to { opacity: 1; }
}

@keyframes pulse-glow {
  0%, 100% { box-shadow: 0 0 5px color-mix(in oklch, var(--theme-primary) 50%, transparent); }
  50% { box-shadow: 0 0 20px color-mix(in oklch, var(--theme-primary) 80%, transparent); }
}

.animate-in { animation-duration: 200ms; animation-fill-mode: both; }
.slide-in-from-right-5 { animation-name: slide-in-from-right; }
.fade-in { animation-name: fade-in; }
.animate-pulse-glow { animation: pulse-glow 2s ease-in-out infinite; }
`;
}

function generateScrollbarStyles(): string {
  return `
/* =============================================================================
   SCROLLBAR STYLING
   ============================================================================= */
::-webkit-scrollbar { width: 8px; height: 8px; }
::-webkit-scrollbar-track { background: transparent; }
::-webkit-scrollbar-thumb {
  background: color-mix(in oklch, var(--theme-primary) 30%, oklch(0.7 0 0));
  border-radius: 4px;
}
::-webkit-scrollbar-thumb:hover {
  background: color-mix(in oklch, var(--theme-primary) 50%, oklch(0.6 0 0));
}

.dark ::-webkit-scrollbar-thumb {
  background: color-mix(in oklch, var(--theme-primary) 30%, oklch(0.4 0 0));
}
.dark ::-webkit-scrollbar-thumb:hover {
  background: color-mix(in oklch, var(--theme-primary) 50%, oklch(0.5 0 0));
}
`;
}

function generateFormStyles(): string {
  return `
/* =============================================================================
   FORM ELEMENTS
   ============================================================================= */
input:focus,
select:focus,
textarea:focus {
  outline: none;
  border-color: var(--theme-primary);
  box-shadow: 0 0 0 3px color-mix(in oklch, var(--theme-primary) 20%, transparent);
}
`;
}

function generateButtonStyles(): string {
  return `
/* =============================================================================
   BUTTON COMPONENTS
   ============================================================================= */
.btn-theme-primary {
  background-color: var(--theme-primary);
  color: white;
  padding: 0.5rem 1rem;
  border-radius: 0.5rem;
  font-weight: 500;
  transition: all 0.2s;
  box-shadow: 0 4px 14px 0 color-mix(in oklch, var(--theme-primary) 25%, transparent);
}
.btn-theme-primary:hover {
  opacity: 0.9;
  transform: translateY(-1px);
  box-shadow: 0 6px 20px 0 color-mix(in oklch, var(--theme-primary) 35%, transparent);
}

.btn-theme-secondary {
  background-color: color-mix(in oklch, var(--theme-primary) 15%, transparent);
  color: var(--theme-primary);
  padding: 0.5rem 1rem;
  border-radius: 0.5rem;
  font-weight: 500;
  transition: all 0.2s;
}
.btn-theme-secondary:hover {
  background-color: color-mix(in oklch, var(--theme-primary) 25%, transparent);
}
`;
}

function generateLinkStyles(): string {
  return `
/* =============================================================================
   LINK STYLES
   ============================================================================= */
.link-theme {
  color: var(--theme-primary);
  text-decoration: none;
  transition: opacity 0.2s;
}
.link-theme:hover {
  opacity: 0.8;
  text-decoration: underline;
}
`;
}

function generateCategoryColorUtilities(): string {
  const opacityLevels = [10, 15, 20, 30];
  let css = `
/* =============================================================================
   CATEGORY COLOR UTILITIES (Hybrid Approach)

   Pre-generated classes for standard opacity levels (10%, 15%, 20%, 30%)
   Fallback custom property for dynamic/edge cases
   ============================================================================= */

/* === BACKGROUND CLASSES === */
`;

  // Background classes per category
  for (const category of CATEGORY_CATALOG) {
    for (const opacity of opacityLevels) {
      css += `.bg-category-${category.name}-${opacity} { background-color: color-mix(in oklch, ${category.color} ${opacity}%, transparent); }\n`;
    }
  }

  css += `
/* === BORDER CLASSES === */
`;

  // Border classes per category
  for (const category of CATEGORY_CATALOG) {
    for (const opacity of opacityLevels) {
      css += `.border-category-${category.name}-${opacity} { border-color: color-mix(in oklch, ${category.color} ${opacity}%, transparent); }\n`;
    }
  }

  css += `
/* === FALLBACK: Custom Property for Dynamic Cases === */
:root { --category-color: transparent; }
`;

  // Fallback utility classes using custom property
  for (const opacity of opacityLevels) {
    css += `.bg-category-dynamic-${opacity} { background-color: color-mix(in oklch, var(--category-color) ${opacity}%, transparent); }\n`;
  }

  return css;
}

// =============================================================================
// MAIN
// =============================================================================

function generateCSS(): string {
  return [
    generateHeader(),
    generateRootVariables(),
    generateDarkModeBase(),
    generateStandardThemes(),
    generateSpecialThemesSection(),
    generateTailwindIntegration(),
    generateBaseStyles(),
    generateUtilityClasses(),
    generateCategoryColorUtilities(),
    generateAnimations(),
    generateScrollbarStyles(),
    generateFormStyles(),
    generateButtonStyles(),
    generateLinkStyles(),
  ].join("\n");
}

function main(): void {
  console.log("🎨 Generating theme CSS...\n");

  const css = generateCSS();
  const outputPath = path.join(__dirname, "..", "app", "globals.css");

  fs.writeFileSync(outputPath, css, "utf-8");

  const standard = getStandardThemes();
  const special = getSpecialThemes();

  console.log("  Standard themes:");
  for (const t of standard) {
    const marker = t.isDefault ? " (default)" : "";
    console.log(`    • ${t.displayName}${marker}`);
  }

  if (special.length > 0) {
    console.log("\n  ✨ Special themes:");
    for (const t of special) {
      console.log(`    • ${t.displayName}`);
    }
  }

  const stats = fs.statSync(outputPath);
  const sizeKb = (stats.size / 1024).toFixed(1);

  console.log(`\n📁 Output: ${outputPath}`);
  console.log(`   Size: ${sizeKb} KB`);
  console.log(`   Themes: ${THEME_CATALOG.length}`);
  console.log("\n✅ Done!\n");
  console.log(
    "⚠️  Do not manually edit globals.css - regenerate with 'npm run generate:css'\n"
  );
}

main();
