/**
 * Auto-Generate Events from Naming Catalog
 *
 * This script reads EVENT_NAMING_CATALOG and creates/updates events in the database.
 * - Creates new events from catalog
 * - Updates existing auto-generated events
 * - Skips manually created events (autoGenerated: false)
 *
 * Run with: npx tsx --tsconfig tsconfig.json src/scripts/generate-events-from-naming.ts
 */

import "dotenv/config";
import { prisma } from "@/lib/db";
import { EVENT_NAMING_CATALOG } from "@/config/event-naming";

async function generateEventsFromNaming() {
  console.log(
    `🔄 Auto-generating ${EVENT_NAMING_CATALOG.length} events from naming catalog...\n`
  );

  let created = 0;
  let updated = 0;
  let skipped = 0;

  for (const naming of EVENT_NAMING_CATALOG) {
    // Resolve all category IDs (first = primary)
    const resolvedCategories: { id: string; name: string }[] = [];
    let categoryMissing = false;
    for (const catName of naming.categories) {
      const cat = await prisma.category.findUnique({ where: { name: catName } });
      if (!cat) {
        console.log(
          `⚠️  Category "${catName}" not found for event "${naming.name}", skipping`
        );
        categoryMissing = true;
        break;
      }
      resolvedCategories.push(cat);
    }
    if (categoryMissing || resolvedCategories.length === 0) {
      skipped++;
      continue;
    }

    // Extract matching fields from ruleConfig
    const config = naming.ruleConfig as Record<string, unknown>;
    const { tithi, maas, nakshatra, sankranti, isAdhikaOnly, monthly } = config;

    // Determine recurrenceType based on ruleType (and optional monthly flag)
    let recurrenceType: "YEARLY_LUNAR" | "YEARLY_SOLAR" | "MONTHLY_LUNAR" | "NONE" =
      "YEARLY_LUNAR";
    if (naming.ruleType === "SOLAR") {
      recurrenceType = "YEARLY_SOLAR";
    } else if (naming.ruleType === "TITHI" && monthly === true) {
      recurrenceType = "MONTHLY_LUNAR";
    } else if (naming.ruleType === "TITHI") {
      recurrenceType = "YEARLY_LUNAR";
    }

    // When maas is an array (multi-month event like Navadurga), leave event.maas null.
    // The recurrence service reads maas directly from ruleConfig in that case.
    const singleMaas = Array.isArray(maas) ? null : maas || null;

    // Build event data
    const eventData: Record<string, unknown> = {
      name: naming.name,
      description: naming.description || null,
      eventType: naming.eventType,
      recurrenceType,

      // Matching criteria
      tithi: tithi || null,
      maas: singleMaas,
      nakshatra: nakshatra || null,
      sankranti: sankranti || null,
      isAdhikaOnly: isAdhikaOnly || false,

      // Rule engine fields
      ruleType: naming.ruleType,
      ruleConfig: naming.ruleConfig,
      namingKey: naming.key,
      autoGenerated: true,

      tags: naming.tags || [],

      // Timing configuration
      timingType: naming.timingType ?? null,
      startTime: naming.startTime ?? null,
      endTime: naming.endTime ?? null,

      // Alternative names
      aliases: naming.aliases ?? [],
    };

    // Look up by namingKey first (stable identifier, survives renames).
    // Fall back to name ONLY if the event has no namingKey yet (legacy events).
    const existing =
      (await prisma.event.findUnique({ where: { namingKey: naming.key } })) ??
      (await prisma.event.findFirst({
        where: {
          name: naming.name,
          namingKey: null,
        },
      }));

    if (existing) {
      if (existing.autoGenerated) {
        // If the name changed, remove any orphan event that already has the new name
        if (existing.name !== naming.name) {
          const orphan = await prisma.event.findFirst({ where: { name: naming.name } });
          if (orphan && orphan.id !== existing.id && orphan.autoGenerated) {
            await prisma.event.delete({ where: { id: orphan.id } });
            console.log(`🗑️  Removed orphan duplicate: ${naming.name}`);
          }
        }

        // Update auto-generated event (including possible name change)
        await prisma.event.update({
          where: { id: existing.id },
          data: eventData as never,
        });
        // Sync categories: replace all existing entries
        await prisma.eventCategory.deleteMany({ where: { eventId: existing.id } });
        for (let i = 0; i < resolvedCategories.length; i++) {
          await prisma.eventCategory.create({
            data: {
              eventId: existing.id,
              categoryId: resolvedCategories[i]!.id,
              sortOrder: i,
            },
          });
        }
        updated++;
        const renamed =
          existing.name !== naming.name ? ` (hernoemd van "${existing.name}")` : "";
        console.log(`✏️  Updated: ${naming.name}${renamed}`);
      } else {
        // Skip manually created event
        skipped++;
        console.log(`⏭️  Skipped (manual): ${naming.name}`);
      }
    } else {
      // Create new event and its categories
      const newEvent = await prisma.event.create({
        data: eventData as never,
      });
      for (let i = 0; i < resolvedCategories.length; i++) {
        await prisma.eventCategory.create({
          data: {
            eventId: newEvent.id,
            categoryId: resolvedCategories[i]!.id,
            sortOrder: i,
          },
        });
      }
      created++;
      console.log(`✅ Created: ${naming.name}`);
    }
  }

  console.log(`\n${"=".repeat(70)}`);
  console.log(`📊 Summary:`);
  console.log(`  Created:  ${created}`);
  console.log(`  Updated:  ${updated}`);
  console.log(`  Skipped:  ${skipped}`);
  console.log(`  Total:    ${EVENT_NAMING_CATALOG.length}`);
  console.log(`${"=".repeat(70)}\n`);

  // Second pass: create EventSeriesEntry records for parent-child relations
  console.log(`\n🔗 Linking child events to parents via EventSeriesEntry...`);
  let linked = 0;
  let linkFailed = 0;

  for (const naming of EVENT_NAMING_CATALOG) {
    if (!naming.parentKeys || naming.parentKeys.length === 0) continue;

    // Look up child by namingKey (stable identifier, survives renames)
    const childEvent = await prisma.event.findUnique({
      where: { namingKey: naming.key },
    });

    if (!childEvent) {
      console.log(`⚠️  Child event niet gevonden voor namingKey: ${naming.key}`);
      linkFailed++;
      continue;
    }

    for (let i = 0; i < naming.parentKeys.length; i++) {
      const parentKey = naming.parentKeys[i]!;
      const parentEvent = await prisma.event.findUnique({
        where: { namingKey: parentKey },
      });

      if (!parentEvent) {
        console.log(`⚠️  Parent event niet gevonden voor namingKey: ${parentKey}`);
        linkFailed++;
        continue;
      }

      await prisma.eventSeriesEntry.upsert({
        where: {
          parentEventId_childEventId: {
            parentEventId: parentEvent.id,
            childEventId: childEvent.id,
          },
        },
        create: {
          parentEventId: parentEvent.id,
          childEventId: childEvent.id,
          dayNumber: naming.dayNumber ?? null,
          sortOrder: naming.dayNumber ?? i,
        },
        update: {
          dayNumber: naming.dayNumber ?? null,
          sortOrder: naming.dayNumber ?? i,
        },
      });
      linked++;
      console.log(
        `   🔗 ${childEvent.name} → ${parentEvent.name}${naming.dayNumber ? ` (dag ${naming.dayNumber})` : ""}`
      );
    }
  }

  if (linked > 0 || linkFailed > 0) {
    console.log(`   Gekoppeld: ${linked}, Mislukt: ${linkFailed}`);
  }

  console.log(`\n✅ Event auto-generation complete!`);
  console.log(`\n⚠️  NEXT STEP: Regenerate occurrences via API`);
  console.log(`   POST http://localhost:3000/api/events/generate-occurrences`);
  console.log(
    `   Body: {"startDate":"2025-01-01", "endDate":"2027-12-31", "replace": true}\n`
  );
}

generateEventsFromNaming()
  .catch((e) => {
    console.error("❌ Error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    process.exit(0);
  });
