/**
 * Auto-Generate Events from Naming Catalog
 *
 * This script reads EVENT_NAMING_CATALOG and creates/updates events in the database.
 * - Creates new events from catalog
 * - Updates existing auto-generated events
 * - Skips manually created events (autoGenerated: false)
 *
 * Run with: npx tsx --tsconfig tsconfig.json src/scripts/generate-events-from-naming.ts
 */

import "dotenv/config";
import { prisma } from "@/lib/db";
import { EVENT_NAMING_CATALOG } from "@/config/event-naming";

async function generateEventsFromNaming() {
  console.log(
    `🔄 Auto-generating ${EVENT_NAMING_CATALOG.length} events from naming catalog...\n`
  );

  let created = 0;
  let updated = 0;
  let skipped = 0;

  for (const naming of EVENT_NAMING_CATALOG) {
    // Find category by name
    const category = await prisma.category.findUnique({
      where: { name: naming.category },
    });

    if (!category) {
      console.log(
        `⚠️  Category "${naming.category}" not found for event "${naming.name}", skipping`
      );
      skipped++;
      continue;
    }

    // Determine recurrenceType based on ruleType
    let recurrenceType: "YEARLY_LUNAR" | "YEARLY_SOLAR" | "NONE" = "YEARLY_LUNAR";
    if (naming.ruleType === "SOLAR") {
      recurrenceType = "YEARLY_SOLAR";
    } else if (naming.ruleType === "TITHI") {
      recurrenceType = "YEARLY_LUNAR";
    }

    // Extract matching fields from ruleConfig
    const config = naming.ruleConfig as Record<string, unknown>;
    const { tithi, maas, nakshatra, sankranti, isAdhikaOnly } = config;

    // When maas is an array (multi-month event like Navadurga), leave event.maas null.
    // The recurrence service reads maas directly from ruleConfig in that case.
    const singleMaas = Array.isArray(maas) ? null : maas || null;

    // Build event data
    const eventData: Record<string, unknown> = {
      name: naming.name,
      description: naming.description || null,
      eventType: naming.eventType,
      recurrenceType,
      importance: naming.importance,
      categoryId: category.id,

      // Matching criteria
      tithi: tithi || null,
      maas: singleMaas,
      nakshatra: nakshatra || null,
      sankranti: sankranti || null,
      isAdhikaOnly: isAdhikaOnly || false,

      // Rule engine fields
      ruleType: naming.ruleType,
      ruleConfig: naming.ruleConfig,
      namingKey: naming.key,
      autoGenerated: true,

      tags: naming.tags || [],
    };

    // Look up by namingKey first (stable identifier, survives renames).
    // Fall back to name ONLY if the event has no namingKey yet (legacy events).
    const existing =
      (await prisma.event.findUnique({ where: { namingKey: naming.key } })) ??
      (await prisma.event.findFirst({
        where: {
          name: naming.name,
          namingKey: null,
        },
      }));

    if (existing) {
      if (existing.autoGenerated) {
        // If the name changed, remove any orphan event that already has the new name
        if (existing.name !== naming.name) {
          const orphan = await prisma.event.findFirst({ where: { name: naming.name } });
          if (orphan && orphan.id !== existing.id && orphan.autoGenerated) {
            await prisma.event.delete({ where: { id: orphan.id } });
            console.log(`🗑️  Removed orphan duplicate: ${naming.name}`);
          }
        }

        // Update auto-generated event (including possible name change)
        await prisma.event.update({
          where: { id: existing.id },
          data: eventData,
        });
        updated++;
        const renamed =
          existing.name !== naming.name ? ` (hernoemd van "${existing.name}")` : "";
        console.log(`✏️  Updated: ${naming.name}${renamed}`);
      } else {
        // Skip manually created event
        skipped++;
        console.log(`⏭️  Skipped (manual): ${naming.name}`);
      }
    } else {
      // Create new event
      await prisma.event.create({
        data: eventData,
      });
      created++;
      console.log(`✅ Created: ${naming.name}`);
    }
  }

  console.log(`\n${"=".repeat(70)}`);
  console.log(`📊 Summary:`);
  console.log(`  Created:  ${created}`);
  console.log(`  Updated:  ${updated}`);
  console.log(`  Skipped:  ${skipped}`);
  console.log(`  Total:    ${EVENT_NAMING_CATALOG.length}`);
  console.log(`${"=".repeat(70)}\n`);

  // Second pass: create EventSeriesEntry records for parent-child relations
  console.log(`\n🔗 Linking child events to parents via EventSeriesEntry...`);
  let linked = 0;
  let linkFailed = 0;

  for (const naming of EVENT_NAMING_CATALOG) {
    if (!naming.parentKeys || naming.parentKeys.length === 0) continue;

    // Look up child by namingKey (stable identifier, survives renames)
    const childEvent = await prisma.event.findUnique({
      where: { namingKey: naming.key },
    });

    if (!childEvent) {
      console.log(`⚠️  Child event niet gevonden voor namingKey: ${naming.key}`);
      linkFailed++;
      continue;
    }

    for (let i = 0; i < naming.parentKeys.length; i++) {
      const parentKey = naming.parentKeys[i]!;
      const parentEvent = await prisma.event.findUnique({
        where: { namingKey: parentKey },
      });

      if (!parentEvent) {
        console.log(`⚠️  Parent event niet gevonden voor namingKey: ${parentKey}`);
        linkFailed++;
        continue;
      }

      await prisma.eventSeriesEntry.upsert({
        where: {
          parentEventId_childEventId: {
            parentEventId: parentEvent.id,
            childEventId: childEvent.id,
          },
        },
        create: {
          parentEventId: parentEvent.id,
          childEventId: childEvent.id,
          dayNumber: naming.dayNumber ?? null,
          sortOrder: naming.dayNumber ?? i,
        },
        update: {
          dayNumber: naming.dayNumber ?? null,
          sortOrder: naming.dayNumber ?? i,
        },
      });
      linked++;
      console.log(
        `   🔗 ${childEvent.name} → ${parentEvent.name}${naming.dayNumber ? ` (dag ${naming.dayNumber})` : ""}`
      );
    }
  }

  if (linked > 0 || linkFailed > 0) {
    console.log(`   Gekoppeld: ${linked}, Mislukt: ${linkFailed}`);
  }

  console.log(`\n✅ Event auto-generation complete!`);
  console.log(`\n⚠️  NEXT STEP: Regenerate occurrences via API`);
  console.log(`   POST http://localhost:3000/api/events/generate-occurrences`);
  console.log(
    `   Body: {"startDate":"2025-01-01", "endDate":"2027-12-31", "replace": true}\n`
  );
}

generateEventsFromNaming()
  .catch((e) => {
    console.error("❌ Error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    process.exit(0);
  });
