import 'dotenv/config';
import { prisma } from '@/lib/db';
import { readFileSync } from 'fs';

interface DrikEvent {
  name: string;
  date: string;
  details: string;
}

async function validateAgainstDrik2025() {
  // Parse Drik Panchang 2025 file
  const drikContent = readFileSync('/home/gerald/projects/Claude/dharma-calendar/events_dp_2025.txt', 'utf-8');
  const lines = drikContent.split('\n');

  const drikEvents: DrikEvent[] = [];
  let currentEvent: Partial<DrikEvent> = {};

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();

    if (!line) {
      if (currentEvent.name && currentEvent.date) {
        drikEvents.push(currentEvent as DrikEvent);
      }
      currentEvent = {};
      continue;
    }

    // Skip month headers and other noise
    if (line.includes('Panchang') || line.startsWith('===')) continue;

    // Check if it's a date line (contains month name and year)
    if (line.match(/\w+\s+\d{1,2},\s+2025/)) {
      currentEvent.date = line;
    } else if (line.match(/^[A-Z]/)) {
      // Likely an event name
      if (!currentEvent.name) {
        currentEvent.name = line;
      } else if (!currentEvent.date) {
        currentEvent.details = line;
      }
    }
  }

  console.log(`\n📊 Parsed ${drikEvents.length} events from Drik Panchang 2025\n`);

  // Get all our events
  const ourEvents = await prisma.event.findMany({
    select: {
      name: true,
      ruleType: true,
      autoGenerated: true,
    },
    orderBy: { name: 'asc' },
  });

  console.log(`📊 We have ${ourEvents.length} events in database\n`);

  // Find missing events
  const ourEventNames = new Set(ourEvents.map(e => e.name.toLowerCase().trim()));
  const missing: DrikEvent[] = [];
  const found: DrikEvent[] = [];

  for (const drikEvent of drikEvents) {
    const normalizedName = drikEvent.name.toLowerCase().trim();

    // Try various name variations
    const variations = [
      normalizedName,
      normalizedName.replace(/\s+/g, ' '),
      normalizedName.replace(' puja', ''),
      normalizedName.replace(' vrat', ''),
      normalizedName.replace(' jayanti', ''),
    ];

    let isFound = false;
    for (const variation of variations) {
      if (ourEventNames.has(variation)) {
        found.push(drikEvent);
        isFound = true;
        break;
      }
    }

    if (!isFound) {
      missing.push(drikEvent);
    }
  }

  console.log(`✅ Found in our database: ${found.length}`);
  console.log(`❌ Missing from our database: ${missing.length}\n`);

  console.log(`\n❌ MISSING EVENTS:\n${'='.repeat(70)}`);
  for (const event of missing) {
    console.log(`${event.name}`);
    console.log(`  ${event.date}`);
    if (event.details) console.log(`  ${event.details}`);
    console.log();
  }

  await prisma.$disconnect();
}

validateAgainstDrik2025().catch(console.error);
