-- CreateEnum
CREATE TYPE "Rashi" AS ENUM ('MESHA', 'VRISHABHA', 'MITHUNA', 'KARKA', 'SIMHA', 'KANYA', 'TULA', 'VRISHCHIKA', 'DHANU', 'MAKARA', 'KUMBHA', 'MEENA');

-- CreateEnum
CREATE TYPE "Sankranti" AS ENUM ('MESHA_SANKRANTI', 'VRISHABHA_SANKRANTI', 'MITHUNA_SANKRANTI', 'KARKA_SANKRANTI', 'SIMHA_SANKRANTI', 'KANYA_SANKRANTI', 'TULA_SANKRANTI', 'VRISHCHIKA_SANKRANTI', 'DHANU_SANKRANTI', 'MAKARA_SANKRANTI', 'KUMBHA_SANKRANTI', 'MEENA_SANKRANTI');

-- AlterTable
ALTER TABLE "DailyInfo" ADD COLUMN     "sankranti" "Sankranti",
ADD COLUMN     "sankrantiTime" TEXT;

-- AlterTable
ALTER TABLE "Event" ADD COLUMN     "sankranti" "Sankranti";
