import { describe, it, expect, beforeEach, vi } from "vitest";
import { prismaMock } from "../../__tests__/helpers/prisma-mock";
import {
  generateOccurrences,
  generateOccurrencesForEvents,
  getRecommendedWindow,
} from "../recurrence";
import { EventType } from "@prisma/client";
import type { Event } from "@prisma/client";

/* eslint-disable @typescript-eslint/no-explicit-any */

// Re-use mock event base
const BASE_EVENT: Event = {
  id: "evt_1",
  name: "Test Event",
  recurrenceType: "YEARLY_LUNAR",
  tithi: "EKADASHI_SHUKLA",
  maas: "PAUSHA",
  description: null,
  eventType: "FESTIVAL",
  createdAt: new Date(),
  updatedAt: new Date(),
  nakshatra: null,
  tags: [],
  aliases: [],
  sankranti: null,
  isAdhikaOnly: false,
  includeAdhika: false,
  ruleType: null,
  ruleConfig: null,
  namingKey: null,
  autoGenerated: false,
  startTime: null,
  endTime: null,
  timingType: null,
};

describe("Recurrence Service Extended", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    prismaMock.dailyInfo.findMany.mockResolvedValue([]);
  });

  const startDate = new Date("2025-01-01");
  const endDate = new Date("2026-12-31");
  const options = { startDate, endDate };

  it("hits all recurrence service branches", async () => {
    // 1. Dynamic Timing Fallback
    const eventStatic: Event = {
      ...BASE_EVENT,
      startTime: new Date("1970-01-01T10:00:00.000Z"),
    };
    prismaMock.dailyInfo.findMany.mockResolvedValueOnce([
      { date: new Date("2025-01-10T00:00:00.000Z"), maas: "PAUSHA" },
    ] as any);
    const res1 = await generateOccurrences(eventStatic, options);
    expect(res1[0]!.startTime).toBe("10:00");

    // 2. applyDynamicTiming early return and dynamic calc
    const eventDynamic: Event = { ...BASE_EVENT, timingType: "NISHITA_KAAL" };
    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      if (args.where.tithi === "EKADASHI_SHUKLA")
        return [{ date: new Date("2025-01-10T00:00:00.000Z"), maas: "PAUSHA" }] as any;
      if (args.where.date?.in)
        return [
          {
            date: new Date("2025-01-10T00:00:00.000Z"),
            sunrise: new Date("1970-01-01T08:00:00.000Z"),
            sunset: new Date("1970-01-01T17:00:00.000Z"),
          },
          {
            date: new Date("2025-01-11T00:00:00.000Z"),
            sunrise: new Date("1970-01-01T08:00:00.000Z"),
          },
        ] as any;
      return [];
    }) as any);
    const res2 = await generateOccurrences(eventDynamic, options);
    expect(res2[0]!.startTime).toBeDefined();

    // 3. Rule fallbacks (SOLAR, NAKSHATRA, MONTHLY_LUNAR, YEARLY_SOLAR)
    expect(
      await generateOccurrences(
        { ...BASE_EVENT, ruleType: "SOLAR", sankranti: null },
        options
      )
    ).toEqual([]);
    expect(
      await generateOccurrences(
        { ...BASE_EVENT, ruleType: "SOLAR", sankranti: "BAD" as any },
        options
      )
    ).toEqual([]);
    expect(
      await generateOccurrences(
        { ...BASE_EVENT, ruleType: "NAKSHATRA", nakshatra: null },
        options
      )
    ).toEqual([]);
    expect(
      await generateOccurrences(
        { ...BASE_EVENT, recurrenceType: "MONTHLY_LUNAR", tithi: null },
        options
      )
    ).toEqual([]);
    expect(
      await generateOccurrences(
        { ...BASE_EVENT, recurrenceType: "YEARLY_SOLAR", sankranti: null },
        options
      )
    ).toEqual([]);
    expect(
      await generateOccurrences(
        { ...BASE_EVENT, recurrenceType: "YEARLY_SOLAR", sankranti: "BAD" as any },
        options
      )
    ).toEqual([]);

    // 4. PRADOSH missing config
    expect(
      await generateOccurrences(
        { ...BASE_EVENT, ruleType: "PRADOSH", ruleConfig: { weekday: 1 } as any },
        options
      )
    ).toEqual([]);
    expect(
      await generateOccurrences(
        { ...BASE_EVENT, ruleType: "PRADOSH", ruleConfig: { paksha: "SHUKLA" } as any },
        options
      )
    ).toEqual([]);

    // 5. AMAVASYA uses udaya tithi rule (no phase correction), same as PURNIMA.
    // Candidates are returned as-is regardless of moonPhasePercent.
    const eventPhase: Event = { ...BASE_EVENT, tithi: "AMAVASYA", maas: null };
    const d1 = new Date(Date.UTC(2025, 4, 12));
    const d3 = new Date(Date.UTC(2026, 5, 10));
    prismaMock.dailyInfo.findMany.mockResolvedValueOnce([
      { date: d1, maas: "PAUSHA", isAdhika: false },
      { date: d3, maas: "MAGHA", isAdhika: false },
    ] as any);
    const res5 = await generateOccurrences(eventPhase, options);
    expect(res5).toHaveLength(2);
    expect(res5[0]!.date.getUTCDate()).toBe(12);
    expect(res5[1]!.date.getUTCDate()).toBe(10);

    // 6. Multi-day duration
    const eventMulti: Event = {
      ...BASE_EVENT,
      ruleConfig: { durationDays: 3 } as any,
      maas: null,
    };
    prismaMock.dailyInfo.findMany.mockResolvedValueOnce([
      {
        date: new Date(Date.UTC(2025, 0, 1)),
        tithiEndTime: new Date("1970-01-01T10:00:00.000Z"),
      },
    ] as any);
    const res6 = await generateOccurrences(eventMulti, options);
    expect(res6[0]!.endDate).toBeDefined();

    // 7. PRADOSH Case 2 logic and sort
    const eventPradosh: Event = {
      ...BASE_EVENT,
      ruleType: "PRADOSH",
      ruleConfig: { paksha: "SHUKLA", weekday: 6 } as any,
    };
    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      if (args.where.tithi?.in?.includes("DWADASHI_SHUKLA"))
        return [
          {
            date: new Date("2025-01-18T00:00:00.000Z"),
            sunset: new Date("1970-01-01T17:00:00.000Z"),
            tithiEndTime: new Date("1970-01-01T15:00:00.000Z"),
            sunrise: new Date("1970-01-01T08:00:00.000Z"),
          },
          {
            date: new Date("2025-01-11T00:00:00.000Z"),
            sunset: new Date("1970-01-01T17:00:00.000Z"),
            tithiEndTime: new Date("1970-01-01T15:00:00.000Z"),
            sunrise: new Date("1970-01-01T08:00:00.000Z"),
          },
          {
            date: new Date("2025-01-25T00:00:00.000Z"),
            sunset: new Date("1970-01-01T17:00:00.000Z"),
            tithiEndTime: new Date("1970-01-01T18:30:00.000Z"),
            sunrise: new Date("1970-01-01T08:00:00.000Z"),
          },
        ] as any;
      return [];
    }) as any);
    const res7 = await generateOccurrences(eventPradosh, options);
    expect(res7).toHaveLength(3);
    expect(res7[0]!.date.getUTCDate()).toBe(11);

    // 8. Batch error — failed events are excluded from results (not deleted on replace)
    prismaMock.dailyInfo.findMany.mockRejectedValueOnce(new Error("Fail"));
    const res8 = await generateOccurrencesForEvents([BASE_EVENT], options);
    expect(res8.results.get(BASE_EVENT.id)).toBeUndefined();
    expect(res8.failedCount).toBe(1);

    // 9. Recommended Windows and Fallbacks
    expect(getRecommendedWindow("YEARLY_SOLAR").yearsAhead).toBe(5);
    expect(getRecommendedWindow("MONTHLY_SOLAR").yearsAhead).toBe(2);
    expect(getRecommendedWindow("UNKNOWN" as any).yearsAhead).toBe(1);
    expect(
      await generateOccurrences(
        { ...BASE_EVENT, recurrenceType: "INVALID" as any, ruleType: null },
        options
      )
    ).toEqual([]);
    expect(
      await generateOccurrences({ ...BASE_EVENT, ruleType: "INVALID" as any }, options)
    ).toEqual([]);

    // 10. Kshaya and VRAT logic
    const eventVrat: Event = {
      ...BASE_EVENT,
      eventType: EventType.VRAT,
      tithi: "NAVAMI_SHUKLA",
    };
    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      if (args.where.tithi === "NAVAMI_SHUKLA") return [] as any;
      if (args.where.tithi === "ASHTAMI_SHUKLA")
        return [
          {
            date: new Date("2025-03-26T00:00:00.000Z"),
            tithiEndTime: new Date("1970-01-01T07:18:00.000Z"),
            sunrise: new Date("1970-01-01T06:33:00.000Z"),
            maas: "PAUSHA",
            isAdhika: false,
          },
        ] as any;
      if (args.where.date?.in)
        return [
          {
            date: new Date("2025-03-25T00:00:00.000Z"),
            tithiEndTime: new Date("1970-01-01T20:00:00.000Z"),
            sunrise: new Date("1970-01-01T06:33:00.000Z"),
          },
        ] as any;
      return [];
    }) as any);
    const res10 = await generateOccurrences(eventVrat, options);
    expect(res10).toHaveLength(1);

    // 11. Nakshatra and Monthly Solar
    const eventNak: Event = { ...BASE_EVENT, ruleType: "NAKSHATRA", nakshatra: "ROHINI" };
    prismaMock.dailyInfo.findMany.mockResolvedValueOnce([
      { date: new Date("2025-01-10T00:00:00.000Z"), maas: "PAUSHA" },
      { date: new Date("2026-01-10T00:00:00.000Z"), maas: "PAUSHA" },
    ] as any);
    expect(await generateOccurrences(eventNak, options)).toHaveLength(2);

    const eventMSolar: Event = { ...BASE_EVENT, recurrenceType: "MONTHLY_SOLAR" };
    prismaMock.dailyInfo.findMany.mockResolvedValueOnce([
      { date: new Date("2025-01-14T00:00:00.000Z"), sankranti: "MAKARA_SANKRANTI" },
    ] as any);
    expect(await generateOccurrences(eventMSolar, options)).toHaveLength(1);
  });
});
