import { describe, it, expect, beforeEach, vi } from "vitest";
import { prismaMock } from "../../__tests__/helpers/prisma-mock";
import { generateOccurrences } from "../recurrence";
import type { Event } from "@prisma/client";

/* eslint-disable @typescript-eslint/no-explicit-any */

const BASE_EVENT: Event = {
  id: "evt_kshaya",
  name: "Kshaya Event",
  recurrenceType: "YEARLY_LUNAR",
  tithi: "EKADASHI_SHUKLA",
  maas: "PAUSHA",
  description: null,
  eventType: "FESTIVAL",
  createdAt: new Date(),
  updatedAt: new Date(),
  nakshatra: null,
  tags: [],
  aliases: [],
  sankranti: null,
  isAdhikaOnly: false,
  includeAdhika: false,
  ruleType: null,
  ruleConfig: null,
  namingKey: null,
  autoGenerated: false,
  startTime: null,
  endTime: null,
  timingType: null,
};

describe("Recurrence Service Kshaya & PRADOSH Edge Cases", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    prismaMock.dailyInfo.findMany.mockResolvedValue([]);
  });

  const startDate = new Date("2025-01-01");
  const endDate = new Date("2025-12-31");
  const options = { startDate, endDate };

  it("covers PRADOSH error for invalid paksha", async () => {
    const event: Event = {
      ...BASE_EVENT,
      ruleType: "PRADOSH",
      ruleConfig: { paksha: "INVALID", weekday: 1 } as any,
    };
    const res = await generateOccurrences(event, options);
    expect(res).toHaveLength(0);
  });

  it("covers PRADOSH error for missing weekday", async () => {
    const event: Event = {
      ...BASE_EVENT,
      ruleType: "PRADOSH",
      ruleConfig: { paksha: "SHUKLA" } as any,
    };
    const res = await generateOccurrences(event, options);
    expect(res).toHaveLength(0);
  });

  it("covers PRADOSH with both pakshas when paksha is omitted", async () => {
    const event: Event = {
      ...BASE_EVENT,
      ruleType: "PRADOSH",
      ruleConfig: { weekday: 1 } as any,
    };

    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      if (
        args.where.tithi?.in?.includes("DWADASHI_SHUKLA") &&
        args.where.tithi?.in?.includes("DWADASHI_KRISHNA")
      ) {
        return [
          {
            date: new Date("2025-01-06T00:00:00.000Z"), // Monday
            sunset: new Date("1970-01-01T17:00:00.000Z"),
            tithiEndTime: new Date("1970-01-01T10:00:00.000Z"),
            sunrise: new Date("1970-01-01T08:00:00.000Z"),
          },
          {
            date: new Date("2025-01-20T00:00:00.000Z"), // Monday
            sunset: new Date("1970-01-01T17:00:00.000Z"),
            tithiEndTime: new Date("1970-01-01T10:00:00.000Z"),
            sunrise: new Date("1970-01-01T08:00:00.000Z"),
          },
        ] as any;
      }
      return [];
    }) as any);

    const res = await generateOccurrences(event, options);
    expect(res).toHaveLength(2);
  });

  it("covers PRADOSH Case 2 (Dwadashi udaya) edge cases", async () => {
    const event: Event = {
      ...BASE_EVENT,
      ruleType: "PRADOSH",
      ruleConfig: { paksha: "SHUKLA", weekday: 1 } as any,
    };

    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      if (args.where.tithi?.in?.includes("DWADASHI_SHUKLA")) {
        return [
          {
            date: new Date("2025-01-06T00:00:00.000Z"), // Monday
            sunset: new Date("1970-01-01T17:00:00.000Z"),
            tithiEndTime: new Date("1970-01-01T17:30:00.000Z"), // Dwadashi ends after sunset but before sunset+45
            sunrise: new Date("1970-01-01T08:00:00.000Z"),
          },
          {
            date: new Date("2025-01-13T00:00:00.000Z"), // Monday
            sunset: new Date("1970-01-01T17:00:00.000Z"),
            tithiEndTime: new Date("1970-01-01T07:00:00.000Z"), // Ends before sunrise (next day) -> skip
            sunrise: new Date("1970-01-01T08:00:00.000Z"),
          },
        ] as any;
      }
      return [];
    }) as any);

    const res = await generateOccurrences(event, options);
    expect(res).toHaveLength(1);
    expect(res[0]!.date.toISOString()).toContain("2025-01-06");
  });

  it("covers PRADOSH Step 2 (Trayodashi udaya) skip when already covered", async () => {
    const event: Event = {
      ...BASE_EVENT,
      ruleType: "PRADOSH",
      ruleConfig: { paksha: "SHUKLA", weekday: 1 } as any,
    };

    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      if (args.where.tithi?.in?.includes("DWADASHI_SHUKLA")) {
        return [
          {
            date: new Date("2025-01-06T00:00:00.000Z"), // Monday
            sunset: new Date("1970-01-01T17:00:00.000Z"),
            tithiEndTime: new Date("1970-01-01T16:00:00.000Z"),
            sunrise: new Date("1970-01-01T08:00:00.000Z"),
          },
        ] as any;
      }
      if (args.where.tithi?.in?.includes("TRAYODASHI_SHUKLA")) {
        return [
          {
            date: new Date("2025-01-06T00:00:00.000Z"), // Already covered
            sunset: new Date("1970-01-01T17:00:00.000Z"),
            tithiEndTime: new Date("1970-01-01T19:00:00.000Z"),
            sunrise: new Date("1970-01-01T08:00:00.000Z"),
          },
          {
            date: new Date("2025-01-13T00:00:00.000Z"), // New one
            sunset: new Date("1970-01-01T17:00:00.000Z"),
            tithiEndTime: new Date("1970-01-01T18:00:00.000Z"),
            sunrise: new Date("1970-01-01T08:00:00.000Z"),
          },
        ] as any;
      }
      return [];
    }) as any);

    const res = await generateOccurrences(event, options);
    expect(res).toHaveLength(2);
  });

  it("covers PRADOSH missing fields", async () => {
    const event: Event = {
      ...BASE_EVENT,
      ruleType: "PRADOSH",
      ruleConfig: { paksha: "SHUKLA", weekday: 1 } as any,
    };

    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      if (args.where.tithi?.in?.includes("DWADASHI_SHUKLA")) {
        return [
          {
            date: new Date("2025-01-06T00:00:00.000Z"),
            sunset: null, // Missing sunset
            tithiEndTime: new Date("1970-01-01T16:00:00.000Z"),
            sunrise: new Date("1970-01-01T08:00:00.000Z"),
          },
          {
            date: new Date("2025-01-13T00:00:00.000Z"),
            sunset: new Date("1970-01-01T17:00:00.000Z"),
            tithiEndTime: null, // null = no valid end time -> skip
            sunrise: new Date("1970-01-01T08:00:00.000Z"),
          },
        ] as any;
      }
      return [];
    }) as any);

    const res = await generateOccurrences(event, options);
    expect(res).toHaveLength(0);
  });

  it("covers KSHAYA fallback logic inside MONTHLY_LUNAR successful path", async () => {
    const event: Event = {
      ...BASE_EVENT,
      recurrenceType: "MONTHLY_LUNAR",
      tithi: "EKADASHI_SHUKLA",
    };

    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      // Step 1: standard query for target tithi returns empty
      if (args.where.tithi === "EKADASHI_SHUKLA") return [];

      // Step 2: kshaya query for predecessor (DASHAMI_SHUKLA)
      if (args.where.tithi === "DASHAMI_SHUKLA") {
        return [
          {
            date: new Date("2025-01-10T00:00:00.000Z"),
            tithiEndTime: new Date("1970-01-01T10:00:00.000Z"), // After sunrise (08:00) -> Ekadashi starts here
            sunrise: new Date("1970-01-01T08:00:00.000Z"),
            maas: "PAUSHA",
          },
        ] as any;
      }
      return [];
    }) as any);

    const res = await generateOccurrences(event, options);
    expect(res).toHaveLength(1);
    expect(res[0]!.startTime).toBe("10:00");
  });

  it("covers KSHAYA fallback with already covered month", async () => {
    const event: Event = {
      ...BASE_EVENT,
      recurrenceType: "MONTHLY_LUNAR",
      tithi: "EKADASHI_SHUKLA",
    };

    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      if (args.where.tithi === "EKADASHI_SHUKLA") {
        return [
          {
            date: new Date("2025-01-09T00:00:00.000Z"),
            tithiEndTime: new Date("1970-01-01T07:00:00.000Z"),
            sunrise: new Date("1970-01-01T08:00:00.000Z"),
          },
        ] as any;
      }
      if (args.where.tithi === "DASHAMI_SHUKLA") {
        return [
          {
            date: new Date("2025-01-10T00:00:00.000Z"), // Close to 9th
            tithiEndTime: new Date("1970-01-01T10:00:00.000Z"),
            sunrise: new Date("1970-01-01T08:00:00.000Z"),
          },
        ] as any;
      }
      return [];
    }) as any);

    const res = await generateOccurrences(event, options);
    expect(res).toHaveLength(1); // Should only have one from the target tithi query
  });
});

describe("Sankashti moonrise-before-sunrise shift", () => {
  const startDate = new Date("2027-01-01");
  const endDate = new Date("2027-12-31");
  const options = { startDate, endDate };

  const sankashtiEvent: Event = {
    ...BASE_EVENT,
    id: "evt_vikata_sankashti",
    name: "Vikata Sankashti Chaturthi",
    recurrenceType: "YEARLY_LUNAR",
    eventType: "VRAT",
    tithi: "CHATURTHI_KRISHNA",
    maas: "VAISHAKHA",
    ruleType: "TITHI",
    ruleConfig: { maas: "VAISHAKHA", tithi: "CHATURTHI_KRISHNA" },
  };

  beforeEach(() => {
    vi.clearAllMocks();
    prismaMock.dailyInfo.findMany.mockResolvedValue([]);
  });

  it("shifts to D-1 when moonrise is after Chaturthi start AND before sunrise (correct DP rule)", async () => {
    // Hypothetical case: Chaturthi starts 00:30, moonrise 00:45, sunrise 06:28
    // Moonrise (00:45) > Chaturthi start (00:30) AND moonrise (00:45) < sunrise (06:28)
    // → moon rises during Chaturthi, before sunrise → belongs to previous night → observe D-1
    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      if (args.where?.tithi === "CHATURTHI_KRISHNA") {
        return [
          {
            date: new Date("2027-04-24T00:00:00.000Z"),
            tithiEndTime: new Date("1970-01-01T02:12:00.000Z"),
            maas: "VAISHAKHA",
            isAdhika: false,
            sunrise: new Date("1970-01-01T06:28:00.000Z"),
            moonrise: new Date("1970-01-01T00:45:00.000Z"),
          },
        ] as any;
      }
      if (args.where?.tithi === "TRITIYA_KRISHNA") return [] as any;
      if (args.where?.date?.in) {
        return [
          {
            date: new Date("2027-04-23T00:00:00.000Z"),
            // Chaturthi starts 00:30 — moonrise (00:45) is AFTER this
            tithiEndTime: new Date("1970-01-01T00:30:00.000Z"),
            sunrise: new Date("1970-01-01T06:31:00.000Z"),
            sunset: new Date("1970-01-01T20:52:00.000Z"),
            tithi: "TRITIYA_KRISHNA",
          },
        ] as any;
      }
      return [] as any;
    }) as any);

    const result = await generateOccurrences(sankashtiEvent, options);

    expect(result).toHaveLength(1);
    expect(result[0]!.date.toISOString()).toContain("2027-04-23");
  });

  it("does NOT shift when moonrise is before Chaturthi start (moon rose before Chaturthi was active)", async () => {
    // Apr 2027 real case: Chaturthi starts 00:51, moonrise 00:45 in our DB
    // Moonrise (00:45) < Chaturthi start (00:51) → moon rose while wrong tithi was active → no shift
    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      if (args.where?.tithi === "CHATURTHI_KRISHNA") {
        return [
          {
            date: new Date("2027-04-24T00:00:00.000Z"),
            tithiEndTime: new Date("1970-01-01T02:12:00.000Z"),
            maas: "VAISHAKHA",
            isAdhika: false,
            sunrise: new Date("1970-01-01T06:28:00.000Z"),
            moonrise: new Date("1970-01-01T00:45:00.000Z"),
          },
        ] as any;
      }
      if (args.where?.tithi === "TRITIYA_KRISHNA") return [] as any;
      if (args.where?.date?.in) {
        return [
          {
            date: new Date("2027-04-23T00:00:00.000Z"),
            // Chaturthi starts 00:51 — moonrise (00:45) is BEFORE this → no shift
            tithiEndTime: new Date("1970-01-01T00:51:00.000Z"),
            sunrise: new Date("1970-01-01T06:31:00.000Z"),
            sunset: new Date("1970-01-01T20:52:00.000Z"),
            tithi: "TRITIYA_KRISHNA",
          },
        ] as any;
      }
      return [] as any;
    }) as any);

    const result = await generateOccurrences(sankashtiEvent, options);

    expect(result).toHaveLength(1);
    expect(result[0]!.date.toISOString()).toContain("2027-04-24");
  });

  it("does NOT shift when moonrise is after sunrise (normal evening moonrise)", async () => {
    // Jan 2027: moonrise 21:46 > sunrise 08:35 — observe on udaya tithi day Jan 25
    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      if (args.where?.tithi === "CHATURTHI_KRISHNA") {
        return [
          {
            date: new Date("2027-01-25T00:00:00.000Z"),
            tithiEndTime: new Date("1970-01-01T01:30:00.000Z"),
            maas: "MAGHA",
            isAdhika: false,
            sunrise: new Date("1970-01-01T08:35:00.000Z"),
            moonrise: new Date("1970-01-01T21:46:00.000Z"),
          },
        ] as any;
      }
      if (args.where?.tithi === "TRITIYA_KRISHNA") return [] as any;
      if (args.where?.date?.in) {
        return [
          {
            date: new Date("2027-01-24T00:00:00.000Z"),
            tithiEndTime: new Date("1970-01-01T03:40:00.000Z"),
            sunrise: new Date("1970-01-01T08:36:00.000Z"),
            sunset: new Date("1970-01-01T17:10:00.000Z"),
            tithi: "TRITIYA_KRISHNA",
          },
        ] as any;
      }
      return [] as any;
    }) as any);

    // Override maas to MAGHA for this test
    const maghaEvent: Event = {
      ...sankashtiEvent,
      maas: "MAGHA",
      ruleConfig: { maas: "MAGHA", tithi: "CHATURTHI_KRISHNA" },
    };
    const result = await generateOccurrences(maghaEvent, options);

    expect(result).toHaveLength(1);
    expect(result[0]!.date.toISOString()).toContain("2027-01-25");
  });
});
