import { describe, it, expect, beforeEach, vi } from "vitest";
import { prismaMock } from "../../__tests__/helpers/prisma-mock";
import { generateOccurrences } from "../recurrence";
import type { Event } from "@prisma/client";

/* eslint-disable @typescript-eslint/no-explicit-any */

const BASE_EVENT: Event = {
  id: "evt_kshaya",
  name: "Kshaya Event",
  recurrenceType: "YEARLY_LUNAR",
  tithi: "EKADASHI_SHUKLA",
  maas: "PAUSHA",
  description: null,
  eventType: "FESTIVAL",
  createdAt: new Date(),
  updatedAt: new Date(),
  nakshatra: null,
  tags: [],
  aliases: [],
  sankranti: null,
  isAdhikaOnly: false,
  includeAdhika: false,
  ruleType: null,
  ruleConfig: null,
  namingKey: null,
  autoGenerated: false,
  startTime: null,
  endTime: null,
  timingType: null,
};

describe("Recurrence Service Kshaya & PRADOSH Edge Cases", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    prismaMock.dailyInfo.findMany.mockResolvedValue([]);
  });

  const startDate = new Date("2025-01-01");
  const endDate = new Date("2025-12-31");
  const options = { startDate, endDate };

  it("covers PRADOSH error for invalid paksha", async () => {
    const event: Event = {
      ...BASE_EVENT,
      ruleType: "PRADOSH",
      ruleConfig: { paksha: "INVALID", weekday: 1 } as any,
    };
    const res = await generateOccurrences(event, options);
    expect(res).toHaveLength(0);
  });

  it("covers PRADOSH error for missing weekday", async () => {
    const event: Event = {
      ...BASE_EVENT,
      ruleType: "PRADOSH",
      ruleConfig: { paksha: "SHUKLA" } as any,
    };
    const res = await generateOccurrences(event, options);
    expect(res).toHaveLength(0);
  });

  it("covers PRADOSH with both pakshas when paksha is omitted", async () => {
    const event: Event = {
      ...BASE_EVENT,
      ruleType: "PRADOSH",
      ruleConfig: { weekday: 1 } as any,
    };

    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      if (
        args.where.tithi?.in?.includes("DWADASHI_SHUKLA") &&
        args.where.tithi?.in?.includes("DWADASHI_KRISHNA")
      ) {
        return [
          {
            date: new Date("2025-01-06T00:00:00.000Z"), // Monday
            sunset: "17:00",
            tithiEndTime: "10:00",
            sunrise: "08:00",
          },
          {
            date: new Date("2025-01-20T00:00:00.000Z"), // Monday
            sunset: "17:00",
            tithiEndTime: "10:00",
            sunrise: "08:00",
          },
        ] as any;
      }
      return [];
    }) as any);

    const res = await generateOccurrences(event, options);
    expect(res).toHaveLength(2);
  });

  it("covers PRADOSH Case 2 (Dwadashi udaya) edge cases", async () => {
    const event: Event = {
      ...BASE_EVENT,
      ruleType: "PRADOSH",
      ruleConfig: { paksha: "SHUKLA", weekday: 1 } as any,
    };

    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      if (args.where.tithi?.in?.includes("DWADASHI_SHUKLA")) {
        return [
          {
            date: new Date("2025-01-06T00:00:00.000Z"), // Monday
            sunset: "17:00",
            tithiEndTime: "17:30", // Dwadashi ends after sunset but before sunset+45
            sunrise: "08:00",
          },
          {
            date: new Date("2025-01-13T00:00:00.000Z"), // Monday
            sunset: "17:00",
            tithiEndTime: "07:00", // Ends before sunrise (next day) -> skip
            sunrise: "08:00",
          },
        ] as any;
      }
      return [];
    }) as any);

    const res = await generateOccurrences(event, options);
    expect(res).toHaveLength(1);
    expect(res[0]!.date.toISOString()).toContain("2025-01-06");
  });

  it("covers PRADOSH Step 2 (Trayodashi udaya) skip when already covered", async () => {
    const event: Event = {
      ...BASE_EVENT,
      ruleType: "PRADOSH",
      ruleConfig: { paksha: "SHUKLA", weekday: 1 } as any,
    };

    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      if (args.where.tithi?.in?.includes("DWADASHI_SHUKLA")) {
        return [
          {
            date: new Date("2025-01-06T00:00:00.000Z"), // Monday
            sunset: "17:00",
            tithiEndTime: "16:00",
            sunrise: "08:00",
          },
        ] as any;
      }
      if (args.where.tithi?.in?.includes("TRAYODASHI_SHUKLA")) {
        return [
          {
            date: new Date("2025-01-06T00:00:00.000Z"), // Already covered
            sunset: "17:00",
            tithiEndTime: "19:00",
            sunrise: "08:00",
          },
          {
            date: new Date("2025-01-13T00:00:00.000Z"), // New one
            sunset: "17:00",
            tithiEndTime: "18:00",
            sunrise: "08:00",
          },
        ] as any;
      }
      return [];
    }) as any);

    const res = await generateOccurrences(event, options);
    expect(res).toHaveLength(2);
  });

  it("covers PRADOSH missing fields", async () => {
    const event: Event = {
      ...BASE_EVENT,
      ruleType: "PRADOSH",
      ruleConfig: { paksha: "SHUKLA", weekday: 1 } as any,
    };

    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      if (args.where.tithi?.in?.includes("DWADASHI_SHUKLA")) {
        return [
          {
            date: new Date("2025-01-06T00:00:00.000Z"),
            sunset: null, // Missing sunset
            tithiEndTime: "16:00",
            sunrise: "08:00",
          },
          {
            date: new Date("2025-01-13T00:00:00.000Z"),
            sunset: "17:00",
            tithiEndTime: "INVALID", // Invalid time
            sunrise: "08:00",
          },
        ] as any;
      }
      return [];
    }) as any);

    const res = await generateOccurrences(event, options);
    expect(res).toHaveLength(0);
  });

  it("covers KSHAYA fallback logic inside MONTHLY_LUNAR successful path", async () => {
    const event: Event = {
      ...BASE_EVENT,
      recurrenceType: "MONTHLY_LUNAR",
      tithi: "EKADASHI_SHUKLA",
    };

    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      // Step 1: standard query for target tithi returns empty
      if (args.where.tithi === "EKADASHI_SHUKLA") return [];

      // Step 2: kshaya query for predecessor (DASHAMI_SHUKLA)
      if (args.where.tithi === "DASHAMI_SHUKLA") {
        return [
          {
            date: new Date("2025-01-10T00:00:00.000Z"),
            tithiEndTime: "10:00", // After sunrise (08:00) -> Ekadashi starts here
            sunrise: "08:00",
            maas: "PAUSHA",
          },
        ] as any;
      }
      return [];
    }) as any);

    const res = await generateOccurrences(event, options);
    expect(res).toHaveLength(1);
    expect(res[0]!.startTime).toBe("10:00");
  });

  it("covers KSHAYA fallback with already covered month", async () => {
    const event: Event = {
      ...BASE_EVENT,
      recurrenceType: "MONTHLY_LUNAR",
      tithi: "EKADASHI_SHUKLA",
    };

    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      if (args.where.tithi === "EKADASHI_SHUKLA") {
        return [
          {
            date: new Date("2025-01-09T00:00:00.000Z"),
            tithiEndTime: "07:00",
            sunrise: "08:00",
          },
        ] as any;
      }
      if (args.where.tithi === "DASHAMI_SHUKLA") {
        return [
          {
            date: new Date("2025-01-10T00:00:00.000Z"), // Close to 9th
            tithiEndTime: "10:00",
            sunrise: "08:00",
          },
        ] as any;
      }
      return [];
    }) as any);

    const res = await generateOccurrences(event, options);
    expect(res).toHaveLength(1); // Should only have one from the target tithi query
  });
});
