import { describe, it, expect, beforeEach, vi } from "vitest";
import { prismaMock } from "../../__tests__/helpers/prisma-mock";
import { generateOccurrences, generateOccurrencesForEvents } from "../recurrence.service";
import { EventType } from "@prisma/client";
import type { Event } from "@prisma/client";

/* eslint-disable @typescript-eslint/no-explicit-any */

const BASE_EVENT: Event = {
  id: "evt_100",
  name: "100% Coverage Event",
  recurrenceType: "YEARLY_LUNAR",
  tithi: "EKADASHI_SHUKLA",
  maas: "PAUSHA",
  description: null,
  eventType: "FESTIVAL",
  createdAt: new Date(),
  updatedAt: new Date(),
  nakshatra: null,
  tags: [],
  aliases: [],
  sankranti: null,
  isAdhikaOnly: false,
  includeAdhika: false,
  ruleType: null,
  ruleConfig: null,
  namingKey: null,
  autoGenerated: false,
  startTime: null,
  endTime: null,
  timingType: null,
};

describe("Recurrence Service 100% Coverage", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    prismaMock.dailyInfo.findMany.mockResolvedValue([]);
  });

  const startDate = new Date("2025-01-01");
  const endDate = new Date("2025-12-31");
  const options = { startDate, endDate };

  it("covers generateOccurrencesForEvents early return", async () => {
    const res = await generateOccurrencesForEvents([], options);
    expect(res.size).toBe(0);
  });

  it("covers applyDynamicTiming missing DailyInfo warning", async () => {
    const event: Event = { ...BASE_EVENT, timingType: "SUNRISE" };
    prismaMock.dailyInfo.findMany.mockResolvedValueOnce([
      { date: new Date("2025-01-10T00:00:00.000Z"), maas: "PAUSHA" },
    ] as any);
    // Second findMany for dynamic timing returns empty
    prismaMock.dailyInfo.findMany.mockResolvedValueOnce([]);

    const res = await generateOccurrences(event, options);
    expect(res[0]!.startTime).toBeUndefined();
  });

  it("covers PRADOSH Case 1 (Step 2) logic branches", async () => {
    const event: Event = {
      ...BASE_EVENT,
      ruleType: "PRADOSH",
      ruleConfig: { paksha: "SHUKLA", weekday: 1 } as any,
    };

    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      // Step 1 (Case 2): DWADASHI
      if (args.where.tithi?.in?.includes("DWADASHI_SHUKLA")) return [];

      // Step 2 (Case 1): TRAYODASHI
      if (args.where.tithi?.in?.includes("TRAYODASHI_SHUKLA")) {
        return [
          {
            date: new Date("2025-01-06T00:00:00.000Z"), // Monday
            sunset: "17:00",
            tithiEndTime: "18:00", // Valid: > sunset-90
            sunrise: "08:00",
          },
          {
            date: new Date("2025-01-13T00:00:00.000Z"), // Monday
            sunset: "17:00",
            tithiEndTime: "07:00", // Valid: < sunrise (extends past midnight)
            sunrise: "08:00",
          },
          {
            date: new Date("2025-01-20T00:00:00.000Z"), // Monday
            sunset: "17:00",
            tithiEndTime: null, // Valid: extends past midnight
            sunrise: "08:00",
          },
        ] as any;
      }
      return [];
    }) as any);

    const res = await generateOccurrences(event, options);
    expect(res).toHaveLength(3);
  });

  it("covers PRADOSH Vriddhi logic", async () => {
    const event: Event = {
      ...BASE_EVENT,
      ruleType: "PRADOSH",
      ruleConfig: { paksha: "SHUKLA", weekday: 1 } as any,
    };

    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      if (args.where.tithi?.in?.includes("DWADASHI_SHUKLA")) return [];
      if (args.where.tithi?.in?.includes("TRAYODASHI_SHUKLA")) {
        return [
          {
            date: new Date("2025-01-06T00:00:00.000Z"), // Monday
            sunset: "17:00",
            tithiEndTime: "10:00",
            sunrise: "08:00",
          },
          {
            date: new Date("2025-01-07T00:00:00.000Z"), // Tuesday
            sunset: "17:00",
            tithiEndTime: "10:00",
            sunrise: "08:00",
          },
        ] as any;
      }
      return [];
    }) as any);

    const res = await generateOccurrences(event, options);
    // Vriddhi means both days are Trayodashi udaya.
    // The first one (Monday) should be valid because Trayodashi spans to the next sunrise.
    expect(res).toHaveLength(1);
  });

  it("covers YEARLY_SOLAR successful path", async () => {
    const event: Event = {
      ...BASE_EVENT,
      recurrenceType: "YEARLY_SOLAR",
      sankranti: "MESHA_SANKRANTI",
    };

    prismaMock.dailyInfo.findMany.mockResolvedValueOnce([
      { date: new Date("2025-04-14T00:00:00.000Z"), sankrantiTime: "10:00" },
    ] as any);

    const res = await generateOccurrences(event, options);
    expect(res).toHaveLength(1);
    expect(res[0]!.startTime).toBe("10:00");
  });

  it("covers EKADASHI logic in applyVratLogic", async () => {
    const event: Event = {
      ...BASE_EVENT,
      eventType: EventType.VRAT,
      tithi: "EKADASHI_SHUKLA",
    };

    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      if (args.where.tithi === "EKADASHI_SHUKLA") {
        return [
          {
            date: new Date("2025-01-10T00:00:00.000Z"),
            tithiEndTime: "10:00",
            sunrise: "08:00",
            maas: "PAUSHA",
            isAdhika: false,
          },
        ] as any;
      }
      if (args.where.date?.in) {
        return [
          {
            date: new Date("2025-01-09T00:00:00.000Z"),
            tithiEndTime: "07:00", // Dashami ends before sunrise -> Ekadashi starts before sunrise
            sunrise: "08:00",
          },
        ] as any;
      }
      return [];
    }) as any);

    const res = await generateOccurrences(event, options);
    expect(res).toHaveLength(1);
  });

  it("covers safety limit and unknown timing type", async () => {
    const event: Event = {
      ...BASE_EVENT,
      recurrenceType: "MONTHLY_LUNAR",
      maas: null,
      timingType: "UNKNOWN" as any,
    };

    // Generate 10 days in different months
    const days = [];
    const months = [
      "PAUSHA",
      "MAGHA",
      "PHALGUNA",
      "CHAITRA",
      "VAISHAKHA",
      "JYESHTHA",
      "ASHADHA",
      "SHRAVANA",
      "BHADRAPADA",
      "ASHVINA",
    ];
    for (let i = 0; i < 10; i++) {
      days.push({
        date: new Date(2025, i, 1),
        maas: months[i],
        isAdhika: false,
      });
    }
    prismaMock.dailyInfo.findMany.mockResolvedValue(days as any);

    const res = await generateOccurrences(event, {
      startDate: new Date("2025-01-01"),
      endDate: new Date("2025-12-31"),
      maxOccurrences: 5,
    });
    expect(res).toHaveLength(5);
  });

  it("covers NISHITA_KAAL dynamic timing logic fully", async () => {
    const event: Event = { ...BASE_EVENT, timingType: "NISHITA_KAAL" };
    prismaMock.dailyInfo.findMany.mockImplementation((async (args: any) => {
      if (args.where.tithi === "EKADASHI_SHUKLA")
        return [{ date: new Date("2025-01-10T00:00:00.000Z"), maas: "PAUSHA" }] as any;
      if (args.where.date?.in) {
        // Mock daily info for today and tomorrow
        return [
          {
            date: new Date("2025-01-10T00:00:00.000Z"),
            sunrise: "08:00",
            sunset: "17:00",
          },
          { date: new Date("2025-01-11T00:00:00.000Z"), sunrise: "08:10" },
        ] as any;
      }
      return [];
    }) as any);

    const res = await generateOccurrences(event, options);
    expect(res[0]!.startTime).toBeDefined();
  });

  it("covers SOLAR rule occurrences successful path", async () => {
    const event: Event = {
      ...BASE_EVENT,
      ruleType: "SOLAR",
      sankranti: "MAKARA_SANKRANTI",
    };

    prismaMock.dailyInfo.findMany.mockResolvedValueOnce([
      { date: new Date("2025-01-14T00:00:00.000Z"), sankrantiTime: "10:00" },
    ] as any);

    const res = await generateOccurrences(event, options);
    expect(res).toHaveLength(1);
    expect(res[0]!.startTime).toBe("10:00");
  });

  it("covers MONTHLY_SOLAR rule occurrences with notes", async () => {
    const event: Event = {
      ...BASE_EVENT,
      recurrenceType: "MONTHLY_SOLAR",
    };

    prismaMock.dailyInfo.findMany.mockResolvedValueOnce([
      {
        date: new Date("2025-01-14T00:00:00.000Z"),
        sankranti: "MAKARA_SANKRANTI",
        sankrantiTime: "10:00",
      },
    ] as any);

    const res = await generateOccurrences(event, options);
    expect(res).toHaveLength(1);
    expect(res[0]!.notes).toBe("MAKARA Sankranti");
  });
});
