/**
 * Event Naming Catalog
 *
 * Single source of truth for event definitions.
 * Events are auto-generated from these rules.
 *
 * Pattern: categories.ts (category definitions)
 * This file follows the same pattern but for events.
 */

export type RuleType =
  | 'TITHI'              // Match specific tithi (Ekadashi, Purnima, etc.)
  | 'SOLAR'              // Match Sankranti (solar transitions)
  | 'NAKSHATRA'          // Match nakshatra
  | 'TITHI_NAKSHATRA'    // Both tithi AND nakshatra
  | 'WEEKDAY_TITHI'      // Specific weekday + tithi
  | 'CUSTOM';            // Complex rules

export interface EventNaming {
  key: string;
  name: string;
  category: string;
  eventType: 'FESTIVAL' | 'PUJA' | 'VRAT' | 'JAYANTI' | 'TITHI' | 'SANKRANTI' | 'ECLIPSE' | 'OTHER';
  importance: 'MAJOR' | 'MODERATE' | 'MINOR';
  ruleType: RuleType;
  ruleConfig: Record<string, any>;
  description?: string;
  tags?: string[];
}

export const EVENT_NAMING_CATALOG: EventNaming[] = [
  // ==========================================================================
  // EKADASHI EVENTS (24 per year - 2 per lunar month)
  // Rule: TITHI with maas + paksha
  // ==========================================================================
  {
    key: 'pausha_putrada_ekadashi',
    name: 'Putrada Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_SHUKLA',
      maas: 'PAUSHA',
    },
    description: 'Ekadashi in Pausha Shukla paksha. Believed to grant sons and general prosperity.',
    tags: ['ekadashi', 'vasten', 'zonen', 'voorspoed'],
  },
  {
    key: 'pausha_saphala_ekadashi',
    name: 'Saphala Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_KRISHNA',
      maas: 'PAUSHA',
    },
    description: 'Means "fruitful/successful". Fasting brings success in all endeavors.',
    tags: ['ekadashi', 'vasten', 'succes'],
  },
  {
    key: 'magha_sattila_ekadashi',
    name: 'Sat-tila Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_KRISHNA',
      maas: 'MAGHA',
    },
    description: 'Offering sesame (til) in seven forms purifies sins.',
    tags: ['ekadashi', 'vasten', 'til', 'sesam'],
  },
  {
    key: 'magha_jaya_ekadashi',
    name: 'Jaya Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_SHUKLA',
      maas: 'MAGHA',
    },
    description: 'Fasting liberates from ignorance and brings spiritual victory (jaya).',
    tags: ['ekadashi', 'vasten', 'overwinning'],
  },
  {
    key: 'phalguna_vijaya_ekadashi',
    name: 'Vijaya Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_KRISHNA',
      maas: 'PHALGUNA',
    },
    description: 'Lord Rama fasted on this day before going to Lanka to rescue Sita.',
    tags: ['ekadashi', 'vasten', 'rama', 'overwinning'],
  },
  {
    key: 'phalguna_amalaki_ekadashi',
    name: 'Amalaki Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_SHUKLA',
      maas: 'PHALGUNA',
    },
    description: 'Dedicated to amalaki (amla) tree, sacred to Lord Vishnu.',
    tags: ['ekadashi', 'vasten', 'amla', 'vishnu'],
  },
  {
    key: 'chaitra_papmochani_ekadashi',
    name: 'Papmochani Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_KRISHNA',
      maas: 'CHAITRA',
    },
    description: 'Means "remover of sins". Powerful Ekadashi that purifies all sins.',
    tags: ['ekadashi', 'vasten', 'zuivering', 'zonden'],
  },
  {
    key: 'chaitra_kamada_ekadashi',
    name: 'Kamada Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_SHUKLA',
      maas: 'CHAITRA',
    },
    description: 'Ekadashi that fulfills all desires (kama). Gandharva was freed from curse.',
    tags: ['ekadashi', 'vasten', 'wensen', 'verlossing'],
  },
  {
    key: 'vaishakha_varuthini_ekadashi',
    name: 'Varuthini Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_KRISHNA',
      maas: 'VAISHAKHA',
    },
    description: 'Removes greatest sins and protects from difficulties.',
    tags: ['ekadashi', 'vasten', 'bescherming'],
  },
  {
    key: 'vaishakha_mohini_ekadashi',
    name: 'Mohini Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_SHUKLA',
      maas: 'VAISHAKHA',
    },
    description: 'Named after Mohini avatar of Vishnu. Very auspicious for liberation.',
    tags: ['ekadashi', 'vasten', 'mohini', 'moksha'],
  },
  {
    key: 'jyeshtha_apara_ekadashi',
    name: 'Apara Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_KRISHNA',
      maas: 'JYESHTHA',
    },
    description: 'Removes sins and grants liberation. Very powerful Ekadashi.',
    tags: ['ekadashi', 'vasten', 'zuivering'],
  },
  {
    key: 'jyeshtha_nirjala_ekadashi',
    name: 'Nirjala Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MAJOR',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_SHUKLA',
      maas: 'JYESHTHA',
    },
    description: 'Most austere Ekadashi - fasting without even water. Bhima\'s Ekadashi.',
    tags: ['ekadashi', 'vasten', 'nirjala', 'bhima'],
  },
  {
    key: 'ashadha_yogini_ekadashi',
    name: 'Yogini Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_KRISHNA',
      maas: 'ASHADHA',
    },
    description: 'Removes sins of many lifetimes and grants spiritual progress.',
    tags: ['ekadashi', 'vasten', 'yoga'],
  },
  {
    key: 'ashadha_devshayani_ekadashi',
    name: 'Devshayani Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MAJOR',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_SHUKLA',
      maas: 'ASHADHA',
    },
    description: 'Start of Chaturmas - four months when Lord Vishnu sleeps.',
    tags: ['ekadashi', 'vasten', 'chaturmas', 'vishnu'],
  },
  {
    key: 'shravana_kamika_ekadashi',
    name: 'Kamika Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_KRISHNA',
      maas: 'SHRAVANA',
    },
    description: 'One of the most important Ekadashis. Grants liberation.',
    tags: ['ekadashi', 'vasten', 'moksha'],
  },
  {
    key: 'shravana_putrada_ekadashi',
    name: 'Putrada Ekadashi (Shravana)',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_SHUKLA',
      maas: 'SHRAVANA',
    },
    description: 'Grants children and removes childlessness.',
    tags: ['ekadashi', 'vasten', 'kinderen'],
  },
  {
    key: 'bhadrapada_aja_ekadashi',
    name: 'Aja Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_KRISHNA',
      maas: 'BHADRAPADA',
    },
    description: 'Removes all sins and grants spiritual elevation.',
    tags: ['ekadashi', 'vasten', 'zuivering'],
  },
  {
    key: 'bhadrapada_parsva_ekadashi',
    name: 'Parsva Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_SHUKLA',
      maas: 'BHADRAPADA',
    },
    description: 'Lord Vishnu turns on His side during sleep. Middle of Chaturmas.',
    tags: ['ekadashi', 'vasten', 'chaturmas'],
  },
  {
    key: 'ashwin_indira_ekadashi',
    name: 'Indira Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_KRISHNA',
      maas: 'ASHWIN',
    },
    description: 'Frees ancestors from suffering and grants peace.',
    tags: ['ekadashi', 'vasten', 'voorouders'],
  },
  {
    key: 'ashwin_papankusha_ekadashi',
    name: 'Papankusha Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_SHUKLA',
      maas: 'ASHWIN',
    },
    description: 'Destroys heaps of sins like a sharp hook.',
    tags: ['ekadashi', 'vasten', 'zuivering'],
  },
  {
    key: 'kartik_rama_ekadashi',
    name: 'Rama Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_KRISHNA',
      maas: 'KARTIK',
    },
    description: 'Grants liberation and removes all sins.',
    tags: ['ekadashi', 'vasten', 'rama'],
  },
  {
    key: 'kartik_prabodhini_ekadashi',
    name: 'Prabodhini Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MAJOR',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_SHUKLA',
      maas: 'KARTIK',
    },
    description: 'End of Chaturmas - Lord Vishnu wakes up. Dev Uthani Ekadashi.',
    tags: ['ekadashi', 'vasten', 'chaturmas', 'dev uthani'],
  },
  {
    key: 'margashirsha_utpanna_ekadashi',
    name: 'Utpanna Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_KRISHNA',
      maas: 'MARGASHIRSHA',
    },
    description: 'Celebrates the birth of Ekadashi Devi. Very powerful.',
    tags: ['ekadashi', 'vasten', 'devi'],
  },
  {
    key: 'margashirsha_mokshada_ekadashi',
    name: 'Mokshada Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MAJOR',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_SHUKLA',
      maas: 'MARGASHIRSHA',
    },
    description: 'Grants liberation (moksha). Also called Vaikuntha Ekadashi in South India.',
    tags: ['ekadashi', 'vasten', 'moksha', 'vaikuntha'],
  },

  // ==========================================================================
  // SANKRANTI EVENTS (12 per year - solar transitions)
  // Rule: SOLAR with sankranti name
  // ==========================================================================
  {
    key: 'makara_sankranti',
    name: 'Makara Sankranti',
    category: 'surya',
    eventType: 'SANKRANTI',
    importance: 'MAJOR',
    ruleType: 'SOLAR',
    ruleConfig: {
      sankranti: 'MAKARA_SANKRANTI',
    },
    description: 'Sun enters Capricorn. Harvest festival, beginning of Uttarayana (northward journey of Sun).',
    tags: ['sankranti', 'zon', 'oogst', 'uttarayana'],
  },
  {
    key: 'kumbha_sankranti',
    name: 'Kumbha Sankranti',
    category: 'surya',
    eventType: 'SANKRANTI',
    importance: 'MODERATE',
    ruleType: 'SOLAR',
    ruleConfig: {
      sankranti: 'KUMBHA_SANKRANTI',
    },
    description: 'Sun enters Aquarius.',
    tags: ['sankranti', 'zon'],
  },
  {
    key: 'meena_sankranti',
    name: 'Meena Sankranti',
    category: 'surya',
    eventType: 'SANKRANTI',
    importance: 'MODERATE',
    ruleType: 'SOLAR',
    ruleConfig: {
      sankranti: 'MEENA_SANKRANTI',
    },
    description: 'Sun enters Pisces.',
    tags: ['sankranti', 'zon'],
  },
  {
    key: 'mesha_sankranti',
    name: 'Mesha Sankranti',
    category: 'surya',
    eventType: 'SANKRANTI',
    importance: 'MAJOR',
    ruleType: 'SOLAR',
    ruleConfig: {
      sankranti: 'MESHA_SANKRANTI',
    },
    description: 'Sun enters Aries. Hindu Solar New Year. Also called Vishu in Kerala.',
    tags: ['sankranti', 'zon', 'nieuwjaar', 'vishu'],
  },
  {
    key: 'vrishabha_sankranti',
    name: 'Vrishabha Sankranti',
    category: 'surya',
    eventType: 'SANKRANTI',
    importance: 'MODERATE',
    ruleType: 'SOLAR',
    ruleConfig: {
      sankranti: 'VRISHABHA_SANKRANTI',
    },
    description: 'Sun enters Taurus.',
    tags: ['sankranti', 'zon'],
  },
  {
    key: 'mithuna_sankranti',
    name: 'Mithuna Sankranti',
    category: 'surya',
    eventType: 'SANKRANTI',
    importance: 'MODERATE',
    ruleType: 'SOLAR',
    ruleConfig: {
      sankranti: 'MITHUNA_SANKRANTI',
    },
    description: 'Sun enters Gemini.',
    tags: ['sankranti', 'zon'],
  },
  {
    key: 'karka_sankranti',
    name: 'Karka Sankranti',
    category: 'surya',
    eventType: 'SANKRANTI',
    importance: 'MAJOR',
    ruleType: 'SOLAR',
    ruleConfig: {
      sankranti: 'KARKA_SANKRANTI',
    },
    description: 'Sun enters Cancer. Beginning of Dakshinayana (southward journey of Sun).',
    tags: ['sankranti', 'zon', 'dakshinayana'],
  },
  {
    key: 'simha_sankranti',
    name: 'Simha Sankranti',
    category: 'surya',
    eventType: 'SANKRANTI',
    importance: 'MODERATE',
    ruleType: 'SOLAR',
    ruleConfig: {
      sankranti: 'SIMHA_SANKRANTI',
    },
    description: 'Sun enters Leo.',
    tags: ['sankranti', 'zon'],
  },
  {
    key: 'kanya_sankranti',
    name: 'Kanya Sankranti',
    category: 'surya',
    eventType: 'SANKRANTI',
    importance: 'MODERATE',
    ruleType: 'SOLAR',
    ruleConfig: {
      sankranti: 'KANYA_SANKRANTI',
    },
    description: 'Sun enters Virgo.',
    tags: ['sankranti', 'zon'],
  },
  {
    key: 'tula_sankranti',
    name: 'Tula Sankranti',
    category: 'surya',
    eventType: 'SANKRANTI',
    importance: 'MODERATE',
    ruleType: 'SOLAR',
    ruleConfig: {
      sankranti: 'TULA_SANKRANTI',
    },
    description: 'Sun enters Libra.',
    tags: ['sankranti', 'zon'],
  },
  {
    key: 'vrishchika_sankranti',
    name: 'Vrishchika Sankranti',
    category: 'surya',
    eventType: 'SANKRANTI',
    importance: 'MODERATE',
    ruleType: 'SOLAR',
    ruleConfig: {
      sankranti: 'VRISHCHIKA_SANKRANTI',
    },
    description: 'Sun enters Scorpio.',
    tags: ['sankranti', 'zon'],
  },
  {
    key: 'dhanu_sankranti',
    name: 'Dhanu Sankranti',
    category: 'surya',
    eventType: 'SANKRANTI',
    importance: 'MODERATE',
    ruleType: 'SOLAR',
    ruleConfig: {
      sankranti: 'DHANU_SANKRANTI',
    },
    description: 'Sun enters Sagittarius.',
    tags: ['sankranti', 'zon'],
  },

  // ==========================================================================
  // PURNIMA EVENTS (12 per year)
  // Rule: TITHI with specific maas
  // ==========================================================================
  {
    key: 'ashadha_guru_purnima',
    name: 'Guru Purnima',
    category: 'general',
    eventType: 'FESTIVAL',
    importance: 'MAJOR',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'PURNIMA',
      maas: 'ASHADHA',
    },
    description: 'Honoring spiritual and academic gurus. Day of Vyasa Purnima.',
    tags: ['purnima', 'guru', 'vyasa', 'leraar'],
  },
  {
    key: 'kartik_kartik_purnima',
    name: 'Kartik Purnima',
    category: 'general',
    eventType: 'FESTIVAL',
    importance: 'MAJOR',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'PURNIMA',
      maas: 'KARTIK',
    },
    description: 'Most auspicious Purnima. Karthigai Deepam in South India.',
    tags: ['purnima', 'deepam', 'licht'],
  },
  {
    key: 'pausha_pausha_purnima',
    name: 'Pausha Purnima',
    category: 'general',
    eventType: 'TITHI',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'PURNIMA',
      maas: 'PAUSHA',
    },
    description: 'Full moon of Pausha month. Auspicious for charity and bathing.',
    tags: ['purnima', 'liefdadigheid'],
  },
  {
    key: 'magha_magha_purnima',
    name: 'Magha Purnima',
    category: 'general',
    eventType: 'TITHI',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'PURNIMA',
      maas: 'MAGHA',
    },
    description: 'Full moon of Magha month. Important for ancestors.',
    tags: ['purnima', 'voorouders'],
  },
  {
    key: 'phalguna_holi_purnima',
    name: 'Holi Purnima',
    category: 'general',
    eventType: 'FESTIVAL',
    importance: 'MAJOR',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'PURNIMA',
      maas: 'PHALGUNA',
    },
    description: 'Full moon before Holi. Holika Dahan performed on this night.',
    tags: ['purnima', 'holi', 'holika dahan'],
  },

  // === ADDITIONAL PURNIMAS ===
  {
    key: 'chaitra_chaitra_purnima',
    name: 'Chaitra Purnima',
    category: 'general',
    eventType: 'TITHI',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'PURNIMA',
      maas: 'CHAITRA',
    },
    description: 'Full moon of Chaitra month. Hanuman Jayanti in some regions.',
    tags: ['purnima'],
  },
  {
    key: 'vaishakha_vaishakha_purnima',
    name: 'Vaishakha Purnima',
    category: 'general',
    eventType: 'TITHI',
    importance: 'MAJOR',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'PURNIMA',
      maas: 'VAISHAKHA',
    },
    description: 'Buddha Purnima. Birth of Lord Buddha.',
    tags: ['purnima', 'buddha'],
  },
  {
    key: 'jyeshtha_jyeshtha_purnima',
    name: 'Jyeshtha Purnima',
    category: 'general',
    eventType: 'TITHI',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'PURNIMA',
      maas: 'JYESHTHA',
    },
    description: 'Full moon of Jyeshtha month. Vat Purnima Vrat.',
    tags: ['purnima', 'vrat'],
  },
  {
    key: 'ashadha_ashadha_purnima',
    name: 'Ashadha Purnima',
    category: 'general',
    eventType: 'TITHI',
    importance: 'MAJOR',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'PURNIMA',
      maas: 'ASHADHA',
    },
    description: 'Guru Purnima. Honoring spiritual teachers.',
    tags: ['purnima', 'guru'],
  },
  {
    key: 'shravana_shravana_purnima',
    name: 'Shravana Purnima',
    category: 'general',
    eventType: 'TITHI',
    importance: 'MAJOR',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'PURNIMA',
      maas: 'SHRAVANA',
    },
    description: 'Raksha Bandhan. Sisters tie rakhi on brothers.',
    tags: ['purnima', 'raksha bandhan'],
  },
  {
    key: 'bhadrapada_bhadrapada_purnima',
    name: 'Bhadrapada Purnima',
    category: 'general',
    eventType: 'TITHI',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'PURNIMA',
      maas: 'BHADRAPADA',
    },
    description: 'Full moon of Bhadrapada month.',
    tags: ['purnima'],
  },
  {
    key: 'ashwina_sharad_purnima',
    name: 'Sharad Purnima',
    category: 'general',
    eventType: 'TITHI',
    importance: 'MAJOR',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'PURNIMA',
      maas: 'ASHWIN',
    },
    description: 'Autumn full moon. Most beautiful moonlight of the year.',
    tags: ['purnima', 'sharad'],
  },
  {
    key: 'margashirsha_margashirsha_purnima',
    name: 'Margashirsha Purnima',
    category: 'general',
    eventType: 'TITHI',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'PURNIMA',
      maas: 'MARGASHIRSHA',
    },
    description: 'Full moon of Margashirsha month. Dattatreya Jayanti.',
    tags: ['purnima'],
  },

  // === EKADASHI (ADDITIONAL) ===
  {
    key: 'shravana_gauna_kamika_ekadashi',
    name: 'Gauna Kamika Ekadashi',
    category: 'vishnu',
    eventType: 'VRAT',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'EKADASHI_KRISHNA',
      maas: 'SHRAVANA',
    },
    description: 'Second Kamika Ekadashi observed in Shravana Krishna paksha.',
    tags: ['ekadashi', 'vasten'],
  },

  // === JAYANTIS (DEITY BIRTHDAYS) ===
  {
    key: 'chaitra_swaminarayan_jayanti',
    name: 'Swaminarayan Jayanti',
    category: 'vishnu',
    eventType: 'JAYANTI',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'NAVAMI_SHUKLA',
      maas: 'CHAITRA',
    },
    description: 'Birth anniversary of Swaminarayan.',
    tags: ['jayanti', 'swaminarayan'],
  },
  {
    key: 'vaishakha_parashurama_jayanti',
    name: 'Parashurama Jayanti',
    category: 'vishnu',
    eventType: 'JAYANTI',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'TRITIYA_SHUKLA',
      maas: 'VAISHAKHA',
    },
    description: 'Birth of Lord Parashurama, 6th avatar of Vishnu.',
    tags: ['jayanti', 'parashurama', 'avatar'],
  },
  {
    key: 'jyeshtha_narada_jayanti',
    name: 'Narada Jayanti',
    category: 'general',
    eventType: 'JAYANTI',
    importance: 'MINOR',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'PRATIPADA_KRISHNA',
      maas: 'JYESHTHA',
    },
    description: 'Birth of Sage Narada.',
    tags: ['jayanti', 'narada', 'rishi'],
  },
  {
    key: 'shravana_gayatri_jayanti',
    name: 'Gayatri Jayanti',
    category: 'general',
    eventType: 'JAYANTI',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'PURNIMA',
      maas: 'SHRAVANA',
    },
    description: 'Appearance day of Gayatri Mantra.',
    tags: ['jayanti', 'gayatri', 'mantra'],
  },
  {
    key: 'bhadrapada_balarama_jayanti',
    name: 'Balarama Jayanti',
    category: 'vishnu',
    eventType: 'JAYANTI',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'SHASHTHI_SHUKLA',
      maas: 'BHADRAPADA',
    },
    description: 'Birth of Lord Balarama, elder brother of Krishna.',
    tags: ['jayanti', 'balarama'],
  },

  // === FESTIVALS ===
  {
    key: 'phalguna_holika_dahan',
    name: 'Holika Dahan',
    category: 'general',
    eventType: 'FESTIVAL',
    importance: 'MAJOR',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'PURNIMA',
      maas: 'PHALGUNA',
    },
    description: 'Bonfire night before Holi. Burning of Holika.',
    tags: ['holi', 'festival', 'vuur'],
  },
  {
    key: 'shravana_hariyali_teej',
    name: 'Hariyali Teej',
    category: 'durga',
    eventType: 'FESTIVAL',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'TRITIYA_SHUKLA',
      maas: 'SHRAVANA',
    },
    description: 'Green Teej. Celebrated by women for marital bliss.',
    tags: ['teej', 'festival', 'vrouwen'],
  },
  {
    key: 'bhadrapada_hartalika_teej',
    name: 'Hartalika Teej',
    category: 'shiva',
    eventType: 'FESTIVAL',
    importance: 'MODERATE',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'TRITIYA_SHUKLA',
      maas: 'BHADRAPADA',
    },
    description: 'Teej dedicated to Shiva and Parvati union.',
    tags: ['teej', 'festival', 'shiva', 'parvati'],
  },
  {
    key: 'kartik_chhath_puja',
    name: 'Chhath Puja',
    category: 'surya',
    eventType: 'FESTIVAL',
    importance: 'MAJOR',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'SHASHTHI_SHUKLA',
      maas: 'KARTIK',
    },
    description: 'Ancient Vedic festival dedicated to Sun God.',
    tags: ['chhath', 'festival', 'surya', 'zon'],
  },
  {
    key: 'kartik_govardhan_puja',
    name: 'Govardhan Puja',
    category: 'krishna',
    eventType: 'FESTIVAL',
    importance: 'MAJOR',
    ruleType: 'TITHI',
    ruleConfig: {
      tithi: 'PRATIPADA_SHUKLA',
      maas: 'KARTIK',
    },
    description: 'Day after Diwali. Worship of Govardhan mountain.',
    tags: ['govardhan', 'festival', 'krishna'],
  },
];
