-- CreateEnum
CREATE TYPE "RuleType" AS ENUM ('TITHI', 'SOLAR', 'NAKSHATRA', 'TITHI_NAKSHATRA', 'WEEKDAY_TITHI', 'CUSTOM');

-- AlterTable
ALTER TABLE "Event" ADD COLUMN     "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "namingKey" TEXT,
ADD COLUMN     "ruleConfig" JSONB,
ADD COLUMN     "ruleType" "RuleType";
